# Implements: REQ-F-ASSETMODEL-002
# Implements: REQ-F-ASSETMODEL-005
"""Asset-type library for the first odd_sdlc slice."""
from __future__ import annotations

from .domain_model import AssetSemanticFacet, AssetTypeProfile


SEMANTIC_FACETS: dict[str, AssetSemanticFacet] = {
    "structured_document": AssetSemanticFacet(
        name="structured_document",
        description="A document-shaped asset with headings, sections, and stable textual structure.",
    ),
    "spec_surface": AssetSemanticFacet(
        name="spec_surface",
        description="A constitutional or bounded specification surface carrying live project truth.",
    ),
    "verification_surface": AssetSemanticFacet(
        name="verification_surface",
        description="A surface that defines, records, or proves verification and qualification work.",
    ),
    "authority_surface": AssetSemanticFacet(
        name="authority_surface",
        description="A surface that declares or stabilizes governing authority for downstream work.",
    ),
    "argument_surface": AssetSemanticFacet(
        name="argument_surface",
        description="A surface organized around claims, rationale, and supporting argument.",
    ),
    "singleton_surface": AssetSemanticFacet(
        name="singleton_surface",
        description="A surface expected to exist as one authoritative instance within the current working scope.",
    ),
    "collection_surface": AssetSemanticFacet(
        name="collection_surface",
        description="A surface represented as a folderized or set-shaped collection rather than one singleton document.",
    ),
    "generated_surface": AssetSemanticFacet(
        name="generated_surface",
        description="A surface expected to evolve through constructive turns while retaining attributable provenance.",
    ),
    "source_surface": AssetSemanticFacet(
        name="source_surface",
        description="A surface whose primary payload is executable source material rather than only descriptive prose.",
    ),
}


ASSET_TYPES: dict[str, AssetTypeProfile] = {
    "spec_document": AssetTypeProfile(
        name="spec_document",
        description="Generic live specification document surface.",
        semantic_facets=("structured_document", "spec_surface"),
        fd_evaluator="generic.spec-document-present",
        fp_gap_description="The specification document is not yet semantically converged for its declared role.",
        fp_descriptive_framing="A specification document carries live project truth for one bounded concern and should remain inspectable, structured, and authoritative within that concern.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "singleton_spec_document": AssetTypeProfile(
        name="singleton_spec_document",
        description="Generic singleton live specification document surface.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface"),
        fd_evaluator="generic.singleton-spec-document-present",
        fp_gap_description="The singleton specification document is not yet semantically converged for its declared concern.",
        fp_descriptive_framing="A singleton specification document is the one authoritative document for a bounded concern in the current workspace and should be stable, inspectable, and govern downstream derivation.",
        specializes=("spec_document",),
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "requirement_collection_surface": AssetTypeProfile(
        name="requirement_collection_surface",
        description="Generic folderized requirement family surface.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "collection_surface"),
        fd_evaluator="generic.requirement-collection-present",
        fp_gap_description="The requirement collection is not yet semantically converged.",
        fp_descriptive_framing="A requirement collection is a folderized set of requirement family surfaces that decomposes current product truth into detailed obligation.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("requirement_family_surface_present",),
    ),
    "proof_artifact": AssetTypeProfile(
        name="proof_artifact",
        description="Generic proof or qualification artifact.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface"),
        fd_evaluator="generic.proof-artifact-present",
        fp_gap_description="The proof artifact does not yet justify the claimed qualification or closure.",
        fp_descriptive_framing="A proof artifact records stable verification or qualification truth for downstream consumers.",
        library_level="generic",
        mutable_default=False,
        proof_hints=("immutable_snapshot",),
        closure_hints=("published_proof_surface",),
    ),
    "derived_structure_surface": AssetTypeProfile(
        name="derived_structure_surface",
        description="Generic generated structural decomposition surface.",
        semantic_facets=("structured_document", "spec_surface", "generated_surface"),
        fd_evaluator="generic.derived-structure-present",
        fp_gap_description="The derived structure surface is not yet semantically converged.",
        fp_descriptive_framing="A derived structure surface captures generated decomposition or planning structure used by downstream work.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "verification_collection_surface": AssetTypeProfile(
        name="verification_collection_surface",
        description="Generic generated verification collection surface.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="generic.verification-collection-present",
        fp_gap_description="The verification collection is not yet semantically converged.",
        fp_descriptive_framing="A verification collection is a generated set of verification or testcase surfaces used to drive downstream proving work.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "design_document_surface": AssetTypeProfile(
        name="design_document_surface",
        description="Generic generated design document surface.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "generated_surface"),
        fd_evaluator="generic.design-document-present",
        fp_gap_description="The design document surface is not yet semantically converged.",
        fp_descriptive_framing="A design document surface records generated design structure, rationale, and implementation boundary for downstream execution.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "authority_document_surface": AssetTypeProfile(
        name="authority_document_surface",
        description="Generic generated authority document surface.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="generic.authority-document-present",
        fp_gap_description="The authority document surface is not yet semantically converged.",
        fp_descriptive_framing="An authority document surface stabilizes downstream proving or qualification expectations for consumers of the generated verification surfaces.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("published_authority_surface",),
    ),
    "scenario_collection_surface": AssetTypeProfile(
        name="scenario_collection_surface",
        description="Generic generated scenario collection surface.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="generic.scenario-collection-present",
        fp_gap_description="The scenario collection surface is not yet semantically converged.",
        fp_descriptive_framing="A scenario collection surface gathers generated scenario bundles used to drive downstream proving and review work.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "release_document_surface": AssetTypeProfile(
        name="release_document_surface",
        description="Generic generated release document surface.",
        semantic_facets=("structured_document", "authority_surface", "argument_surface", "generated_surface"),
        fd_evaluator="generic.release-document-present",
        fp_gap_description="The release document surface is not yet semantically converged.",
        fp_descriptive_framing="A release document surface summarizes current readiness, dependencies, proof posture, and publishable release position for the current asset graph.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("published_release_surface",),
    ),
    "stack_profile_surface": AssetTypeProfile(
        name="stack_profile_surface",
        description="Generic generated implementation or test stack profile surface.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "generated_surface"),
        fd_evaluator="generic.stack-profile-present",
        fp_gap_description="The stack profile surface is not yet semantically converged.",
        fp_descriptive_framing="A stack profile surface selects and explains the concrete technical stack for one bounded branch of the current asset graph.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "module_structure_surface": AssetTypeProfile(
        name="module_structure_surface",
        description="Generic generated module structure surface.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="generic.module-structure-present",
        fp_gap_description="The module structure surface is not yet semantically converged.",
        fp_descriptive_framing="A module structure surface defines the current generated module decomposition and ownership boundary for a bounded SDLC branch.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "archive_evidence_surface": AssetTypeProfile(
        name="archive_evidence_surface",
        description="Generic generated archive evidence surface.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="generic.archive-evidence-present",
        fp_gap_description="The archive evidence surface is not yet semantically converged.",
        fp_descriptive_framing="An archive evidence surface explains how archived test or sandbox evidence is structured, compared, and governed for downstream proof.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("published_archive_evidence_surface",),
    ),
    "source_code_surface": AssetTypeProfile(
        name="source_code_surface",
        description="Generic generated source-code surface.",
        semantic_facets=("collection_surface", "generated_surface", "source_surface"),
        fd_evaluator="generic.source-code-present",
        fp_gap_description="The source-code surface is not yet semantically converged.",
        fp_descriptive_framing="A source-code surface materializes executable implementation modules for one bounded branch of the current asset graph.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("published_source_code_surface",),
    ),
    "intent_doc": AssetTypeProfile(
        name="intent_doc",
        description="Singleton intent surface for the project line.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The intent surface is not yet semantically converged.",
        fp_descriptive_framing="An intent document states why the project exists, its governing commitments, outcomes, and constraints.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_intent_surface",),
    ),
    "product_doc": AssetTypeProfile(
        name="product_doc",
        description="Singleton product definition surface.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The product surface is not yet semantically converged.",
        fp_descriptive_framing="A product document defines what the product is, its terms, and the current end-state being built.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_product_surface",),
    ),
    "goal_surface": AssetTypeProfile(
        name="goal_surface",
        description="Current bounded wave of work.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The goals surface is not yet semantically converged.",
        fp_descriptive_framing="A goals surface captures the current bounded wave of work without becoming permanent constitutional law.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_goal_surface",),
    ),
    "requirement_surface": AssetTypeProfile(
        name="requirement_surface",
        description="Folderized requirement family surface.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "collection_surface", "generated_surface"),
        fd_evaluator="requirements-boundary-sources-present",
        fp_gap_description="The requirement surface is not yet semantically converged.",
        fp_descriptive_framing="A requirement surface is a folderized set of requirement family files that decompose the current product definition.",
        specializes=("requirement_collection_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("requirement_family_surface_present",),
    ),
    "proof_surface": AssetTypeProfile(
        name="proof_surface",
        description="Stable proof or qualification artifact.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface"),
        fd_evaluator="requirements-boundary-sources-present",
        fp_gap_description="The proof surface does not yet justify qualification closure.",
        fp_descriptive_framing="A proof surface records stable verification or qualification truth for downstream consumers.",
        specializes=("proof_artifact",),
        library_level="specialized",
        mutable_default=False,
        proof_hints=("immutable_snapshot",),
        closure_hints=("published_proof_surface",),
    ),
    "feature_decomp_surface": AssetTypeProfile(
        name="feature_decomp_surface",
        description="Generated feature decomposition surface for the current requirement set.",
        semantic_facets=("structured_document", "spec_surface", "generated_surface"),
        fd_evaluator="feature-decomp-dependency-surfaces-present",
        fp_gap_description="The feature decomposition surface is not yet semantically converged.",
        fp_descriptive_framing="A feature decomposition surface groups the current requirements into coherent downstream build structure.",
        specializes=("derived_structure_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("feature_decomposition_surface_present",),
    ),
    "uat_testcases_surface": AssetTypeProfile(
        name="uat_testcases_surface",
        description="Generated UAT testcase collection for the current requirement set.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "collection_surface", "generated_surface"),
        fd_evaluator="uat-testcases-dependency-surfaces-present",
        fp_gap_description="The UAT testcase surface is not yet semantically converged.",
        fp_descriptive_framing="A UAT testcase surface is a generated collection of operator-facing acceptance scenarios derived from the current requirements.",
        specializes=("verification_collection_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("uat_testcase_surface_present",),
    ),
    "design_surface": AssetTypeProfile(
        name="design_surface",
        description="Generated odd_sdlc design surface derived from requirements and feature decomposition.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "generated_surface"),
        fd_evaluator="design-dependency-surfaces-present",
        fp_gap_description="The design surface is not yet semantically converged.",
        fp_descriptive_framing="A design surface explains how the current requirement and feature decomposition set should be realized in the current tenant line.",
        specializes=("design_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("design_surface_present",),
    ),
    "review_assessment_surface": AssetTypeProfile(
        name="review_assessment_surface",
        description="Generated review assessment surface derived from the current design surface.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="review-assessment-dependency-surfaces-present",
        fp_gap_description="The review assessment surface is not yet semantically converged.",
        fp_descriptive_framing="A review assessment surface records attributable reviewer findings, concerns, and proposed deltas against the current subject under review.",
        specializes=("authority_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("review_assessment_surface_present",),
    ),
    "consensus_decision_surface": AssetTypeProfile(
        name="consensus_decision_surface",
        description="Generated consensus decision surface reduced from the current review assessment surface.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="consensus-decision-dependency-surfaces-present",
        fp_gap_description="The consensus decision surface is not yet semantically converged.",
        fp_descriptive_framing="A consensus decision surface records the current round decision, quorum posture, and next-action expectations for the subject under review.",
        specializes=("authority_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("consensus_decision_surface_present",),
    ),
    "reviewed_design_surface": AssetTypeProfile(
        name="reviewed_design_surface",
        description="Generated reviewed design surface derived from the current design and consensus decision surfaces.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "generated_surface"),
        fd_evaluator="reviewed-design-dependency-surfaces-present",
        fp_gap_description="The reviewed design surface is not yet semantically converged.",
        fp_descriptive_framing="A reviewed design surface carries the current design after an explicit consensus review round has been reduced and applied.",
        specializes=("design_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("reviewed_design_surface_present",),
    ),
    "testcase_authority_surface": AssetTypeProfile(
        name="testcase_authority_surface",
        description="Generated testcase authority surface derived from the current UAT testcase collection.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="testcase-authority-dependency-surfaces-present",
        fp_gap_description="The testcase authority surface is not yet semantically converged.",
        fp_descriptive_framing="A testcase authority surface stabilizes which generated testcase collection currently counts as authoritative for downstream proving and operator review.",
        specializes=("authority_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("testcase_authority_surface_present",),
    ),
    "scenario_surface": AssetTypeProfile(
        name="scenario_surface",
        description="Generated scenario collection derived from the current requirement and design surfaces.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="scenario-dependency-surfaces-present",
        fp_gap_description="The scenario surface is not yet semantically converged.",
        fp_descriptive_framing="A scenario surface is a generated collection of runtime and proving scenarios derived from the current requirements and design.",
        specializes=("scenario_collection_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("scenario_surface_present",),
    ),
    "release_surface": AssetTypeProfile(
        name="release_surface",
        description="Generated release readiness surface derived from the current requirements, design, scenarios, testcase authority, and archived test evidence.",
        semantic_facets=("structured_document", "authority_surface", "argument_surface", "generated_surface"),
        fd_evaluator="release-dependency-surfaces-present",
        fp_gap_description="The release surface is not yet semantically converged.",
        fp_descriptive_framing="A release surface summarizes whether the current requirement, design, scenario, testcase authority, and archived test evidence state is ready for release-oriented downstream work.",
        specializes=("release_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("release_surface_present",),
    ),
    "test_design_surface": AssetTypeProfile(
        name="test_design_surface",
        description="Generated recursive test-SDLC design surface derived from the current design and scenario surfaces.",
        semantic_facets=("structured_document", "verification_surface", "argument_surface", "generated_surface"),
        fd_evaluator="test-design-dependency-surfaces-present",
        fp_gap_description="The test design surface is not yet semantically converged.",
        fp_descriptive_framing="A test design surface explains the recursive test SDLC, what is being proved, and how sandbox and test-module work will be generated.",
        specializes=("design_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("test_design_surface_present",),
    ),
    "test_stack_profile": AssetTypeProfile(
        name="test_stack_profile",
        description="Generated test stack profile selecting the concrete stack for the current recursive test branch.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "generated_surface"),
        fd_evaluator="test-stack-profile-dependency-surfaces-present",
        fp_gap_description="The test stack profile is not yet semantically converged.",
        fp_descriptive_framing="A test stack profile selects the concrete stack and harness conventions for the current generated test branch, for example pytest-based sandbox qualification or Playwright-based UI qualification.",
        specializes=("stack_profile_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("test_stack_profile_present",),
    ),
    "test_module_surface": AssetTypeProfile(
        name="test_module_surface",
        description="Generated test module structure surface for the current recursive test branch.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="test-module-dependency-surfaces-present",
        fp_gap_description="The test module surface is not yet semantically converged.",
        fp_descriptive_framing="A test module surface defines the generated test module structure, including harness layout, module boundaries, and intended ownership.",
        specializes=("module_structure_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("test_module_surface_present",),
    ),
    "test_run_archive_surface": AssetTypeProfile(
        name="test_run_archive_surface",
        description="Generated archive evidence surface for the current sandbox and comparative test-run model.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "generated_surface"),
        fd_evaluator="test-run-archive-dependency-surfaces-present",
        fp_gap_description="The test run archive surface is not yet semantically converged.",
        fp_descriptive_framing="A test run archive surface defines how sandbox runs, runtime snapshots, and comparative artifacts are retained and interpreted as governed evidence.",
        specializes=("archive_evidence_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("test_run_archive_surface_present",),
    ),
    "implementation_design_surface": AssetTypeProfile(
        name="implementation_design_surface",
        description="Generated recursive implementation-SDLC design surface derived from the current design and scenario surfaces.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "generated_surface"),
        fd_evaluator="implementation-design-dependency-surfaces-present",
        fp_gap_description="The implementation design surface is not yet semantically converged.",
        fp_descriptive_framing="An implementation design surface explains the recursive implementation SDLC, what code is being built, and how module and package work will be generated.",
        specializes=("design_document_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("implementation_design_surface_present",),
    ),
    "implementation_stack_profile": AssetTypeProfile(
        name="implementation_stack_profile",
        description="Generated implementation stack profile selecting the concrete stack for the current recursive implementation branch.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "generated_surface"),
        fd_evaluator="implementation-stack-profile-dependency-surfaces-present",
        fp_gap_description="The implementation stack profile is not yet semantically converged.",
        fp_descriptive_framing="An implementation stack profile selects the concrete language, packaging, and runtime conventions for the current generated implementation branch.",
        specializes=("stack_profile_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("implementation_stack_profile_present",),
    ),
    "implementation_module_surface": AssetTypeProfile(
        name="implementation_module_surface",
        description="Generated implementation module structure surface for the current recursive implementation branch.",
        semantic_facets=("structured_document", "spec_surface", "collection_surface", "generated_surface"),
        fd_evaluator="implementation-module-dependency-surfaces-present",
        fp_gap_description="The implementation module surface is not yet semantically converged.",
        fp_descriptive_framing="An implementation module surface defines the generated implementation package layout, module boundaries, and ownership for the current branch.",
        specializes=("module_structure_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("implementation_module_surface_present",),
    ),
    "code_surface": AssetTypeProfile(
        name="code_surface",
        description="Generated executable code package for the current recursive implementation branch.",
        semantic_facets=("collection_surface", "generated_surface", "source_surface"),
        fd_evaluator="code-dependency-surfaces-present",
        fp_gap_description="The code surface is not yet semantically converged.",
        fp_descriptive_framing="A code surface is the generated implementation package for the current bounded branch, with executable modules that realize the design and module decomposition.",
        specializes=("source_code_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("code_surface_present",),
    ),
}
