# Implements: REQ-F-ASSETMODEL-002
# Implements: REQ-F-ASSETMODEL-005
"""Asset-type library for the first odd_sdlc slice."""
from __future__ import annotations

from .domain_model import AssetSemanticFacet, AssetTypeProfile


SEMANTIC_FACETS: dict[str, AssetSemanticFacet] = {
    "structured_document": AssetSemanticFacet(
        name="structured_document",
        description="A document-shaped asset with headings, sections, and stable textual structure.",
    ),
    "spec_surface": AssetSemanticFacet(
        name="spec_surface",
        description="A constitutional or bounded specification surface carrying live project truth.",
    ),
    "verification_surface": AssetSemanticFacet(
        name="verification_surface",
        description="A surface that defines, records, or proves verification and qualification work.",
    ),
    "authority_surface": AssetSemanticFacet(
        name="authority_surface",
        description="A surface that declares or stabilizes governing authority for downstream work.",
    ),
    "argument_surface": AssetSemanticFacet(
        name="argument_surface",
        description="A surface organized around claims, rationale, and supporting argument.",
    ),
    "singleton_surface": AssetSemanticFacet(
        name="singleton_surface",
        description="A surface expected to exist as one authoritative instance within the current working scope.",
    ),
    "collection_surface": AssetSemanticFacet(
        name="collection_surface",
        description="A surface represented as a folderized or set-shaped collection rather than one singleton document.",
    ),
    "generated_surface": AssetSemanticFacet(
        name="generated_surface",
        description="A surface expected to evolve through constructive turns while retaining attributable provenance.",
    ),
}


ASSET_TYPES: dict[str, AssetTypeProfile] = {
    "spec_document": AssetTypeProfile(
        name="spec_document",
        description="Generic live specification document surface.",
        semantic_facets=("structured_document", "spec_surface"),
        fd_evaluator="generic.spec-document-present",
        fp_gap_description="The specification document is not yet semantically converged for its declared role.",
        fp_descriptive_framing="A specification document carries live project truth for one bounded concern and should remain inspectable, structured, and authoritative within that concern.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "singleton_spec_document": AssetTypeProfile(
        name="singleton_spec_document",
        description="Generic singleton live specification document surface.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface"),
        fd_evaluator="generic.singleton-spec-document-present",
        fp_gap_description="The singleton specification document is not yet semantically converged for its declared concern.",
        fp_descriptive_framing="A singleton specification document is the one authoritative document for a bounded concern in the current workspace and should be stable, inspectable, and govern downstream derivation.",
        specializes=("spec_document",),
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "requirement_collection_surface": AssetTypeProfile(
        name="requirement_collection_surface",
        description="Generic folderized requirement family surface.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "collection_surface"),
        fd_evaluator="generic.requirement-collection-present",
        fp_gap_description="The requirement collection is not yet semantically converged.",
        fp_descriptive_framing="A requirement collection is a folderized set of requirement family surfaces that decomposes current product truth into detailed obligation.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("requirement_family_surface_present",),
    ),
    "proof_artifact": AssetTypeProfile(
        name="proof_artifact",
        description="Generic proof or qualification artifact.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface"),
        fd_evaluator="generic.proof-artifact-present",
        fp_gap_description="The proof artifact does not yet justify the claimed qualification or closure.",
        fp_descriptive_framing="A proof artifact records stable verification or qualification truth for downstream consumers.",
        library_level="generic",
        mutable_default=False,
        proof_hints=("immutable_snapshot",),
        closure_hints=("published_proof_surface",),
    ),
    "derived_structure_surface": AssetTypeProfile(
        name="derived_structure_surface",
        description="Generic generated structural decomposition surface.",
        semantic_facets=("structured_document", "spec_surface", "generated_surface"),
        fd_evaluator="generic.derived-structure-present",
        fp_gap_description="The derived structure surface is not yet semantically converged.",
        fp_descriptive_framing="A derived structure surface captures generated decomposition or planning structure used by downstream work.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "verification_collection_surface": AssetTypeProfile(
        name="verification_collection_surface",
        description="Generic generated verification collection surface.",
        semantic_facets=("structured_document", "verification_surface", "collection_surface", "generated_surface"),
        fd_evaluator="generic.verification-collection-present",
        fp_gap_description="The verification collection is not yet semantically converged.",
        fp_descriptive_framing="A verification collection is a generated set of verification or testcase surfaces used to drive downstream proving work.",
        library_level="generic",
        proof_hints=("post_mortem_event_audit",),
    ),
    "intent_doc": AssetTypeProfile(
        name="intent_doc",
        description="Singleton intent surface for the project line.",
        semantic_facets=("structured_document", "spec_surface", "argument_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The intent surface is not yet semantically converged.",
        fp_descriptive_framing="An intent document states why the project exists, its governing commitments, outcomes, and constraints.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_intent_surface",),
    ),
    "product_doc": AssetTypeProfile(
        name="product_doc",
        description="Singleton product definition surface.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The product surface is not yet semantically converged.",
        fp_descriptive_framing="A product document defines what the product is, its terms, and the current end-state being built.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_product_surface",),
    ),
    "goal_surface": AssetTypeProfile(
        name="goal_surface",
        description="Current bounded wave of work.",
        semantic_facets=("structured_document", "spec_surface", "singleton_surface", "generated_surface"),
        fd_evaluator="bootstrap-input-set-present",
        fp_gap_description="The goals surface is not yet semantically converged.",
        fp_descriptive_framing="A goals surface captures the current bounded wave of work without becoming permanent constitutional law.",
        specializes=("singleton_spec_document",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("single_authoritative_goal_surface",),
    ),
    "requirement_surface": AssetTypeProfile(
        name="requirement_surface",
        description="Folderized requirement family surface.",
        semantic_facets=("structured_document", "spec_surface", "authority_surface", "collection_surface", "generated_surface"),
        fd_evaluator="requirements-boundary-sources-present",
        fp_gap_description="The requirement surface is not yet semantically converged.",
        fp_descriptive_framing="A requirement surface is a folderized set of requirement family files that decompose the current product definition.",
        specializes=("requirement_collection_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("requirement_family_surface_present",),
    ),
    "proof_surface": AssetTypeProfile(
        name="proof_surface",
        description="Stable proof or qualification artifact.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface"),
        fd_evaluator="requirements-boundary-sources-present",
        fp_gap_description="The proof surface does not yet justify qualification closure.",
        fp_descriptive_framing="A proof surface records stable verification or qualification truth for downstream consumers.",
        specializes=("proof_artifact",),
        library_level="specialized",
        mutable_default=False,
        proof_hints=("immutable_snapshot",),
        closure_hints=("published_proof_surface",),
    ),
    "feature_decomp_surface": AssetTypeProfile(
        name="feature_decomp_surface",
        description="Generated feature decomposition surface for the current requirement set.",
        semantic_facets=("structured_document", "spec_surface", "generated_surface"),
        fd_evaluator="feature-decomp-dependency-surfaces-present",
        fp_gap_description="The feature decomposition surface is not yet semantically converged.",
        fp_descriptive_framing="A feature decomposition surface groups the current requirements into coherent downstream build structure.",
        specializes=("derived_structure_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("feature_decomposition_surface_present",),
    ),
    "uat_testcases_surface": AssetTypeProfile(
        name="uat_testcases_surface",
        description="Generated UAT testcase collection for the current requirement set.",
        semantic_facets=("structured_document", "verification_surface", "authority_surface", "collection_surface", "generated_surface"),
        fd_evaluator="uat-testcases-dependency-surfaces-present",
        fp_gap_description="The UAT testcase surface is not yet semantically converged.",
        fp_descriptive_framing="A UAT testcase surface is a generated collection of operator-facing acceptance scenarios derived from the current requirements.",
        specializes=("verification_collection_surface",),
        library_level="specialized",
        proof_hints=("post_mortem_event_audit",),
        closure_hints=("uat_testcase_surface_present",),
    ),
}
