# Implements: REQ-F-ODDSDLC-003
# Implements: REQ-F-ODDSDLC-004
# Implements: REQ-F-ASSETMODEL-005
"""Bounded constructor turn for the first odd_sdlc slice."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from genesis.events import EventContext, EventStream, emit

from .asset_types import ASSET_TYPES
from .workspace_assets import checkpoint_for_path, relative_file_uri


def _read_json(path: Path, *, label: str) -> dict[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{label} must be a JSON object")
    return raw


def _workspace_asset_path(workspace_root: Path, target_asset: str) -> Path:
    mapping = {
        "intent_surface": workspace_root / "specification" / "INTENT.md",
        "product_surface": workspace_root / "specification" / "PRODUCT.md",
        "goal_surface": workspace_root / "specification" / "GOALS.md",
        "requirement_surface": workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md",
    }
    try:
        return mapping[target_asset]
    except KeyError as exc:
        raise ValueError(f"Unsupported target_asset {target_asset!r}") from exc


def _construct_intent(workspace_root: Path) -> str:
    product = (workspace_root / "specification" / "PRODUCT.md").read_text(encoding="utf-8").strip()
    goals = (workspace_root / "specification" / "GOALS.md").read_text(encoding="utf-8").strip()
    return "\n".join(
        (
            "# Intent",
            "",
            "This intent surface is regenerated by the bounded odd_sdlc constructor turn.",
            "",
            "## Purpose",
            "`odd_sdlc` exists to prove that asset-typed GTL/ABG apps can be built, run, audited, reset, and rerun.",
            "",
            "## Bound Sources",
            f"- Product surface present: {'yes' if product else 'no'}",
            f"- Goals surface present: {'yes' if goals else 'no'}",
            "",
            "## Runtime Contract",
            "- graph functions are the constructive carrier",
            "- ABG owns runtime facts",
            "- post-mortem event audit is the primary proof surface",
            "",
        )
    )


def _construct_product(workspace_root: Path) -> str:
    goals = (workspace_root / "specification" / "GOALS.md").read_text(encoding="utf-8").strip()
    return "\n".join(
        (
            "# Product",
            "",
            "This product surface is regenerated by the bounded odd_sdlc constructor turn.",
            "",
            "The current product is a toy app with one real canonical use case:",
            "- install a clean sandbox",
            "- run one graph-function call",
            "- ingest the result",
            "- audit emitted facts",
            "- reset and rerun",
            "",
            "## Current Goals Snapshot",
            goals,
            "",
        )
    )


def _construct_goals() -> str:
    return "\n".join(
        (
            "# Goals",
            "",
            "- keep the sandbox use case canonical",
            "- keep the first graph-function call repeatable",
            "- prove runtime truth by event audit",
            "",
        )
    )


def _construct_requirements() -> str:
    return "\n".join(
        (
            "# Generated Bootstrap Requirements",
            "",
            "The first odd_sdlc slice must remain installable, runnable, auditable, and resettable.",
            "",
            "## Generated Expectations",
            "- the installed sandbox opens a graph call",
            "- assess-result closes that call lawfully",
            "- reset clears runtime state without corrupting the workspace",
            "",
        )
    )


def _constructed_content(target_asset: str, workspace_root: Path) -> str:
    if target_asset == "intent_surface":
        return _construct_intent(workspace_root)
    if target_asset == "product_surface":
        return _construct_product(workspace_root)
    if target_asset == "goal_surface":
        return _construct_goals()
    if target_asset == "requirement_surface":
        return _construct_requirements()
    raise ValueError(f"Unsupported target_asset {target_asset!r}")


def construct_manifest(manifest_path: str | Path, *, workspace_root: str | Path = ".") -> dict[str, Any]:
    workspace = Path(workspace_root).resolve()
    manifest_file = Path(manifest_path).resolve()
    manifest = _read_json(manifest_file, label=f"manifest file {manifest_file}")

    target_asset = manifest.get("target_asset")
    result_path = manifest.get("result_path")
    failing_evaluators = manifest.get("failing_evaluators", [])
    if not isinstance(target_asset, str) or not target_asset:
        raise ValueError("manifest must provide target_asset")
    if not isinstance(result_path, str) or not result_path:
        raise ValueError("manifest must provide result_path")
    if not isinstance(failing_evaluators, list) or not failing_evaluators:
        raise ValueError("manifest must provide failing_evaluators")

    target_path = _workspace_asset_path(workspace, target_asset)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    previous_checkpoint = checkpoint_for_path(target_path)
    content = _constructed_content(target_asset, workspace)
    target_path.write_text(content, encoding="utf-8")
    current_checkpoint = checkpoint_for_path(target_path)

    declared_asset_type = {
        "intent_surface": "intent_doc",
        "product_surface": "product_doc",
        "goal_surface": "goal_surface",
        "requirement_surface": "requirement_surface",
    }[target_asset]
    asset_profile = ASSET_TYPES[declared_asset_type]

    emit(
        "asset_checkpoint_updated",
        {
            "asset_id": target_asset,
            "asset_uri": relative_file_uri(target_path, workspace_root=workspace),
            "declared_asset_type": declared_asset_type,
            "mutable": asset_profile.mutable_default,
            "manifest_id": manifest["manifest_id"],
            "edge": manifest["edge"],
            "target_path": str(target_path),
            "previous_checkpoint": previous_checkpoint.to_dict(),
            "current_checkpoint": current_checkpoint.to_dict(),
        },
        stream=EventStream.open(workspace),
        context=EventContext(
            workflow_version=manifest.get("workflow_version", "unknown"),
            run_id=manifest.get("run_id"),
            job_id=manifest.get("job_id"),
            graph_function_id=manifest.get("graph_function_id"),
            materialization_id=manifest.get("materialization_id"),
            call_id=manifest.get("call_id"),
            vector_id=manifest.get("vector_id"),
            aggregate_type="graph_call",
            aggregate_id=manifest.get("call_id"),
            correlation_id=manifest.get("call_id"),
        ),
    )

    primary_evaluator = failing_evaluators[0]["name"]
    payload = {
        "edge": manifest["edge"],
        "actor": "odd_sdlc_constructor",
        "assessments": [
            {
                "evaluator": primary_evaluator,
                "result": "pass",
                "evidence": f"updated {target_path.relative_to(workspace)} via bounded constructor turn",
            }
        ],
    }
    result_file = Path(result_path)
    result_file.parent.mkdir(parents=True, exist_ok=True)
    result_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    return {
        "status": "constructed",
        "manifest_path": str(manifest_file),
        "target_asset": target_asset,
        "target_path": str(target_path),
        "result_path": str(result_file),
        "actor": payload["actor"],
        "evaluator": primary_evaluator,
    }
