# Implements: REQ-F-RUNTIME-003
# Implements: REQ-F-ODDSDLC-004
"""Deterministic checks for the first odd_sdlc slice."""
from __future__ import annotations

import argparse
from pathlib import Path


INTENT_MARKER = "This intent surface is regenerated by the bounded odd_sdlc constructor turn."
PRODUCT_MARKER = "This product surface is regenerated by the bounded odd_sdlc constructor turn."
GOALS_MARKER = "These goals are regenerated by the bounded odd_sdlc constructor turn."
REQUIREMENTS_MARKER = "This requirement surface is regenerated by the bounded odd_sdlc constructor turn."
FEATURE_DECOMP_MARKER = "This feature decomposition surface is regenerated by the bounded odd_sdlc constructor turn."
UAT_TESTCASES_MARKER = "This UAT testcase surface is regenerated by the bounded odd_sdlc constructor turn."
DESIGN_MARKER = "This design surface is regenerated by the bounded odd_sdlc constructor turn."
TESTCASE_AUTHORITY_MARKER = "This testcase authority surface is regenerated by the bounded odd_sdlc constructor turn."
SCENARIO_MARKER = "This scenario surface is regenerated by the bounded odd_sdlc constructor turn."
IMPLEMENTATION_DESIGN_MARKER = "This implementation design surface is regenerated by the bounded odd_sdlc constructor turn."
IMPLEMENTATION_STACK_PROFILE_MARKER = "This implementation stack profile is regenerated by the bounded odd_sdlc constructor turn."
IMPLEMENTATION_MODULE_MARKER = "This implementation module surface is regenerated by the bounded odd_sdlc constructor turn."
CODE_MARKER = "This code surface is regenerated by the bounded odd_sdlc constructor turn."
RELEASE_MARKER = "This release surface is regenerated by the bounded odd_sdlc constructor turn."
TEST_DESIGN_MARKER = "This test design surface is regenerated by the bounded odd_sdlc constructor turn."
TEST_STACK_PROFILE_MARKER = "This test stack profile is regenerated by the bounded odd_sdlc constructor turn."
TEST_MODULE_MARKER = "This test module surface is regenerated by the bounded odd_sdlc constructor turn."
TEST_RUN_ARCHIVE_MARKER = "This test run archive surface is regenerated by the bounded odd_sdlc constructor turn."


def _require_exists(path: Path) -> bool:
    return path.exists()


def _contains_text(path: Path, marker: str) -> bool:
    return path.exists() and marker in path.read_text(encoding="utf-8")


def bootstrap_input_set_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    return 0 if all(_require_exists(path) for path in required) else 1


def product_dependency_surfaces_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if _contains_text(required[0], INTENT_MARKER) else 1


def goal_dependency_surfaces_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if _contains_text(required[0], INTENT_MARKER) and _contains_text(required[1], PRODUCT_MARKER) else 1


def requirements_boundary_sources_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
        workspace_root / "specification" / "requirements",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if (
        _contains_text(required[0], INTENT_MARKER)
        and _contains_text(required[1], PRODUCT_MARKER)
        and _contains_text(required[2], GOALS_MARKER)
        and _contains_text(workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md", REQUIREMENTS_MARKER)
    ) else 1


def feature_decomp_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    return 0 if _contains_text(requirements_file, REQUIREMENTS_MARKER) else 1


def uat_testcases_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    return 0 if _contains_text(requirements_file, REQUIREMENTS_MARKER) else 1


def design_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    feature_decomp_file = workspace_root / "build_tenants" / "common" / "design" / "20-generated-feature-decomp.md"
    return 0 if (
        _contains_text(requirements_file, REQUIREMENTS_MARKER)
        and _contains_text(feature_decomp_file, FEATURE_DECOMP_MARKER)
    ) else 1


def testcase_authority_dependency_surfaces_present(workspace_root: Path) -> int:
    uat_testcases_file = workspace_root / "specification" / "scenarios" / "20-generated-uat-testcases.md"
    scenario_file = workspace_root / "specification" / "scenarios" / "40-generated-scenarios.md"
    return 0 if (
        _contains_text(uat_testcases_file, UAT_TESTCASES_MARKER)
        and _contains_text(scenario_file, SCENARIO_MARKER)
    ) else 1


def scenario_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    design_file = workspace_root / "build_tenants" / "common" / "design" / "30-generated-odd-design.md"
    return 0 if (
        _contains_text(requirements_file, REQUIREMENTS_MARKER)
        and _contains_text(design_file, DESIGN_MARKER)
    ) else 1


def implementation_design_dependency_surfaces_present(workspace_root: Path) -> int:
    design_file = workspace_root / "build_tenants" / "common" / "design" / "30-generated-odd-design.md"
    scenario_file = workspace_root / "specification" / "scenarios" / "40-generated-scenarios.md"
    return 0 if (
        _contains_text(design_file, DESIGN_MARKER)
        and _contains_text(scenario_file, SCENARIO_MARKER)
    ) else 1


def implementation_stack_profile_dependency_surfaces_present(workspace_root: Path) -> int:
    implementation_design_file = workspace_root / "build_tenants" / "odd_method" / "python" / "design" / "40-generated-implementation-design.md"
    return 0 if _contains_text(implementation_design_file, IMPLEMENTATION_DESIGN_MARKER) else 1


def implementation_module_dependency_surfaces_present(workspace_root: Path) -> int:
    implementation_design_file = workspace_root / "build_tenants" / "odd_method" / "python" / "design" / "40-generated-implementation-design.md"
    implementation_stack_file = workspace_root / "build_tenants" / "odd_method" / "python" / "design" / "40-generated-implementation-stack.md"
    return 0 if (
        _contains_text(implementation_design_file, IMPLEMENTATION_DESIGN_MARKER)
        and _contains_text(implementation_stack_file, IMPLEMENTATION_STACK_PROFILE_MARKER)
    ) else 1


def code_dependency_surfaces_present(workspace_root: Path) -> int:
    implementation_module_file = workspace_root / "build_tenants" / "odd_method" / "python" / "design" / "40-generated-implementation-modules.md"
    implementation_stack_file = workspace_root / "build_tenants" / "odd_method" / "python" / "design" / "40-generated-implementation-stack.md"
    return 0 if (
        _contains_text(implementation_module_file, IMPLEMENTATION_MODULE_MARKER)
        and _contains_text(implementation_stack_file, IMPLEMENTATION_STACK_PROFILE_MARKER)
    ) else 1


def release_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    design_file = workspace_root / "build_tenants" / "common" / "design" / "30-generated-odd-design.md"
    scenario_file = workspace_root / "specification" / "scenarios" / "40-generated-scenarios.md"
    code_surface_root = workspace_root / "build_tenants" / "odd_method" / "python" / "code" / "odd_generated_impl"
    testcase_authority_file = workspace_root / "specification" / "scenarios" / "30-generated-testcase-authority.md"
    test_run_archive_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "test_env" / "50-generated-run-archive.md"
    return 0 if (
        _contains_text(requirements_file, REQUIREMENTS_MARKER)
        and _contains_text(design_file, DESIGN_MARKER)
        and _contains_text(scenario_file, SCENARIO_MARKER)
        and code_surface_root.is_dir()
        and _contains_text(code_surface_root / "__init__.py", CODE_MARKER)
        and _contains_text(testcase_authority_file, TESTCASE_AUTHORITY_MARKER)
        and _contains_text(test_run_archive_file, TEST_RUN_ARCHIVE_MARKER)
    ) else 1


def test_design_dependency_surfaces_present(workspace_root: Path) -> int:
    design_file = workspace_root / "build_tenants" / "common" / "design" / "30-generated-odd-design.md"
    scenario_file = workspace_root / "specification" / "scenarios" / "40-generated-scenarios.md"
    return 0 if (
        _contains_text(design_file, DESIGN_MARKER)
        and _contains_text(scenario_file, SCENARIO_MARKER)
    ) else 1


def test_stack_profile_dependency_surfaces_present(workspace_root: Path) -> int:
    test_design_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "design" / "40-generated-test-design.md"
    return 0 if _contains_text(test_design_file, TEST_DESIGN_MARKER) else 1


def test_module_dependency_surfaces_present(workspace_root: Path) -> int:
    test_design_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "design" / "40-generated-test-design.md"
    test_stack_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "test_env" / "40-generated-test-stack.md"
    return 0 if (
        _contains_text(test_design_file, TEST_DESIGN_MARKER)
        and _contains_text(test_stack_file, TEST_STACK_PROFILE_MARKER)
    ) else 1


def test_run_archive_dependency_surfaces_present(workspace_root: Path) -> int:
    test_module_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "test_env" / "tests" / "40-generated-test-modules.md"
    test_stack_file = workspace_root / "build_tenants" / "odd_sdlc" / "python" / "test_env" / "40-generated-test-stack.md"
    return 0 if (
        _contains_text(test_module_file, TEST_MODULE_MARKER)
        and _contains_text(test_stack_file, TEST_STACK_PROFILE_MARKER)
    ) else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="odd_sdlc.fd_checks")
    parser.add_argument(
        "check",
        choices=(
            "bootstrap-input-set-present",
            "product-dependency-surfaces-present",
            "goal-dependency-surfaces-present",
            "requirements-boundary-sources-present",
            "feature-decomp-dependency-surfaces-present",
            "uat-testcases-dependency-surfaces-present",
            "design-dependency-surfaces-present",
            "testcase-authority-dependency-surfaces-present",
            "scenario-dependency-surfaces-present",
            "implementation-design-dependency-surfaces-present",
            "implementation-stack-profile-dependency-surfaces-present",
            "implementation-module-dependency-surfaces-present",
            "code-dependency-surfaces-present",
            "release-dependency-surfaces-present",
            "test-design-dependency-surfaces-present",
            "test-stack-profile-dependency-surfaces-present",
            "test-module-dependency-surfaces-present",
            "test-run-archive-dependency-surfaces-present",
        ),
    )
    parser.add_argument("--workspace", default=".")
    args = parser.parse_args(argv)

    workspace_root = Path(args.workspace).resolve()
    if args.check == "bootstrap-input-set-present":
        return bootstrap_input_set_present(workspace_root)
    if args.check == "product-dependency-surfaces-present":
        return product_dependency_surfaces_present(workspace_root)
    if args.check == "goal-dependency-surfaces-present":
        return goal_dependency_surfaces_present(workspace_root)
    if args.check == "feature-decomp-dependency-surfaces-present":
        return feature_decomp_dependency_surfaces_present(workspace_root)
    if args.check == "uat-testcases-dependency-surfaces-present":
        return uat_testcases_dependency_surfaces_present(workspace_root)
    if args.check == "design-dependency-surfaces-present":
        return design_dependency_surfaces_present(workspace_root)
    if args.check == "testcase-authority-dependency-surfaces-present":
        return testcase_authority_dependency_surfaces_present(workspace_root)
    if args.check == "scenario-dependency-surfaces-present":
        return scenario_dependency_surfaces_present(workspace_root)
    if args.check == "implementation-design-dependency-surfaces-present":
        return implementation_design_dependency_surfaces_present(workspace_root)
    if args.check == "implementation-stack-profile-dependency-surfaces-present":
        return implementation_stack_profile_dependency_surfaces_present(workspace_root)
    if args.check == "implementation-module-dependency-surfaces-present":
        return implementation_module_dependency_surfaces_present(workspace_root)
    if args.check == "code-dependency-surfaces-present":
        return code_dependency_surfaces_present(workspace_root)
    if args.check == "release-dependency-surfaces-present":
        return release_dependency_surfaces_present(workspace_root)
    if args.check == "test-design-dependency-surfaces-present":
        return test_design_dependency_surfaces_present(workspace_root)
    if args.check == "test-stack-profile-dependency-surfaces-present":
        return test_stack_profile_dependency_surfaces_present(workspace_root)
    if args.check == "test-module-dependency-surfaces-present":
        return test_module_dependency_surfaces_present(workspace_root)
    if args.check == "test-run-archive-dependency-surfaces-present":
        return test_run_archive_dependency_surfaces_present(workspace_root)
    return requirements_boundary_sources_present(workspace_root)


if __name__ == "__main__":
    raise SystemExit(main())
