# Implements: REQ-F-RUNTIME-003
# Implements: REQ-F-ODDSDLC-004
# Implements: REQ-F-ODDSDLC-031
"""Shared deterministic-evaluator contracts for the retained odd_sdlc proving subset."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FdEvaluatorContract:
    evaluator_name: str
    cli_name: str
    description: str


FD_EVALUATOR_CONTRACTS: dict[str, FdEvaluatorContract] = {
    "bootstrap_input_set_present": FdEvaluatorContract(
        evaluator_name="bootstrap_input_set_present",
        cli_name="bootstrap-input-set-present",
        description="The bootstrap input set exists and carries the three singleton specification surfaces.",
    ),
    "product_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="product_dependency_surfaces_present",
        cli_name="product-dependency-surfaces-present",
        description="The product derivation sources exist and the intent surface has already been regenerated by the bounded constructor chain.",
    ),
    "goal_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="goal_dependency_surfaces_present",
        cli_name="goal-dependency-surfaces-present",
        description="The goal derivation sources exist and both intent and product surfaces have already been regenerated by the bounded constructor chain.",
    ),
    "goal_surface_authority_validated": FdEvaluatorContract(
        evaluator_name="goal_surface_authority_validated",
        cli_name="goal-surface-authority-validated",
        description="The generated goals surface retains the imported intent identifiers and does not silently drop live intent authority.",
    ),
    "requirements_boundary_sources_present": FdEvaluatorContract(
        evaluator_name="requirements_boundary_sources_present",
        cli_name="requirements-boundary-sources-present",
        description="Intent, product, and goals have already been regenerated and the requirement surface root exists.",
    ),
    "requirement_scope_complete": FdEvaluatorContract(
        evaluator_name="requirement_scope_complete",
        cli_name="requirement-scope-complete",
        description="The generated requirement surface carries forward the full live requirement inventory rather than silently narrowing scope.",
    ),
    "feature_decomp_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="feature_decomp_dependency_surfaces_present",
        cli_name="feature-decomp-dependency-surfaces-present",
        description="The feature decomposition derivation depends on a regenerated requirement surface.",
    ),
    "uat_testcases_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="uat_testcases_dependency_surfaces_present",
        cli_name="uat-testcases-dependency-surfaces-present",
        description="The UAT testcase derivation depends on a regenerated requirement surface.",
    ),
    "design_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="design_dependency_surfaces_present",
        cli_name="design-dependency-surfaces-present",
        description="The design derivation depends on regenerated requirement and feature decomposition surfaces.",
    ),
    "review_assessment_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="review_assessment_dependency_surfaces_present",
        cli_name="review-assessment-dependency-surfaces-present",
        description="The review assessment derivation depends on a regenerated design surface.",
    ),
    "consensus_decision_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="consensus_decision_dependency_surfaces_present",
        cli_name="consensus-decision-dependency-surfaces-present",
        description="The consensus decision derivation depends on a regenerated review assessment surface.",
    ),
    "reviewed_design_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="reviewed_design_dependency_surfaces_present",
        cli_name="reviewed-design-dependency-surfaces-present",
        description="The reviewed design derivation depends on regenerated design and consensus decision surfaces.",
    ),
    "testcase_authority_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="testcase_authority_dependency_surfaces_present",
        cli_name="testcase-authority-dependency-surfaces-present",
        description="The testcase authority qualification depends on regenerated UAT testcase and scenario surfaces.",
    ),
    "scenario_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="scenario_dependency_surfaces_present",
        cli_name="scenario-dependency-surfaces-present",
        description="The scenario derivation depends on regenerated requirement and design surfaces.",
    ),
    "implementation_design_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="implementation_design_dependency_surfaces_present",
        cli_name="implementation-design-dependency-surfaces-present",
        description="The implementation design derivation depends on regenerated design and scenario surfaces.",
    ),
    "implementation_stack_profile_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="implementation_stack_profile_dependency_surfaces_present",
        cli_name="implementation-stack-profile-dependency-surfaces-present",
        description="The implementation stack profile derivation depends on a regenerated implementation design surface.",
    ),
    "implementation_module_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="implementation_module_dependency_surfaces_present",
        cli_name="implementation-module-dependency-surfaces-present",
        description="The implementation module derivation depends on regenerated implementation design and implementation stack profile surfaces.",
    ),
    "code_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="code_dependency_surfaces_present",
        cli_name="code-dependency-surfaces-present",
        description="The code derivation depends on regenerated implementation module and implementation stack profile surfaces.",
    ),
    "code_traceability_present": FdEvaluatorContract(
        evaluator_name="code_traceability_present",
        cli_name="code-traceability-present",
        description="The generated code surface carries explicit Implements traces for the requirements claimed by the implementation branch and contains no orphan generated source files.",
    ),
    "release_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="release_dependency_surfaces_present",
        cli_name="release-dependency-surfaces-present",
        description="The release derivation depends on regenerated requirement, design, scenario, code, testcase authority, and archived test-evidence surfaces.",
    ),
    "test_design_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="test_design_dependency_surfaces_present",
        cli_name="test-design-dependency-surfaces-present",
        description="The test design derivation depends on regenerated design and scenario surfaces.",
    ),
    "test_stack_profile_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="test_stack_profile_dependency_surfaces_present",
        cli_name="test-stack-profile-dependency-surfaces-present",
        description="The test stack profile derivation depends on a regenerated test design surface.",
    ),
    "test_module_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="test_module_dependency_surfaces_present",
        cli_name="test-module-dependency-surfaces-present",
        description="The test module derivation depends on regenerated test design and test stack profile surfaces.",
    ),
    "test_run_archive_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="test_run_archive_dependency_surfaces_present",
        cli_name="test-run-archive-dependency-surfaces-present",
        description="The archive-evidence derivation depends on regenerated test module and test stack profile surfaces.",
    ),
    "test_traceability_present": FdEvaluatorContract(
        evaluator_name="test_traceability_present",
        cli_name="test-traceability-present",
        description="The generated test surface carries explicit Validates traces for the requirements claimed by the test branch and contains no orphan generated test files.",
    ),
    "deployment_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="deployment_dependency_surfaces_present",
        cli_name="deployment-dependency-surfaces-present",
        description="The deployment derivation depends on a regenerated release readiness surface.",
    ),
    "runtime_observation_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="runtime_observation_dependency_surfaces_present",
        cli_name="runtime-observation-dependency-surfaces-present",
        description="The runtime observation derivation depends on regenerated deployment and archived test-evidence surfaces.",
    ),
    "retrofit_plan_dependency_surfaces_present": FdEvaluatorContract(
        evaluator_name="retrofit_plan_dependency_surfaces_present",
        cli_name="retrofit-plan-dependency-surfaces-present",
        description="The retrofit planning derivation depends on regenerated runtime observation and release surfaces.",
    ),
}
FD_EVALUATOR_CONTRACTS_BY_CLI_NAME: dict[str, FdEvaluatorContract] = {
    contract.cli_name: contract for contract in FD_EVALUATOR_CONTRACTS.values()
}


def fd_contract(evaluator_name: str) -> FdEvaluatorContract:
    return FD_EVALUATOR_CONTRACTS[evaluator_name]


def fd_contract_from_cli(cli_name: str) -> FdEvaluatorContract:
    return FD_EVALUATOR_CONTRACTS_BY_CLI_NAME[cli_name]


def fd_cli_name(evaluator_name: str) -> str:
    return fd_contract(evaluator_name).cli_name


def fd_binding(evaluator_name: str) -> str:
    return f"exec://python -m odd_sdlc.fd_checks {fd_cli_name(evaluator_name)} --workspace ."
