# Implements: REQ-F-RUNTIME-003
# Implements: REQ-F-ODDSDLC-004
"""Deterministic checks for the first odd_sdlc slice."""
from __future__ import annotations

import argparse
from pathlib import Path


INTENT_MARKER = "This intent surface is regenerated by the bounded odd_sdlc constructor turn."
PRODUCT_MARKER = "This product surface is regenerated by the bounded odd_sdlc constructor turn."
GOALS_MARKER = "These goals are regenerated by the bounded odd_sdlc constructor turn."
REQUIREMENTS_MARKER = "This requirement surface is regenerated by the bounded odd_sdlc constructor turn."


def _require_exists(path: Path) -> bool:
    return path.exists()


def _contains_text(path: Path, marker: str) -> bool:
    return path.exists() and marker in path.read_text(encoding="utf-8")


def bootstrap_input_set_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    return 0 if all(_require_exists(path) for path in required) else 1


def product_dependency_surfaces_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if _contains_text(required[0], INTENT_MARKER) else 1


def goal_dependency_surfaces_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if _contains_text(required[0], INTENT_MARKER) and _contains_text(required[1], PRODUCT_MARKER) else 1


def requirements_boundary_sources_present(workspace_root: Path) -> int:
    required = (
        workspace_root / "specification" / "INTENT.md",
        workspace_root / "specification" / "PRODUCT.md",
        workspace_root / "specification" / "GOALS.md",
        workspace_root / "specification" / "requirements",
    )
    if not all(_require_exists(path) for path in required):
        return 1
    return 0 if (
        _contains_text(required[0], INTENT_MARKER)
        and _contains_text(required[1], PRODUCT_MARKER)
        and _contains_text(required[2], GOALS_MARKER)
        and _contains_text(workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md", REQUIREMENTS_MARKER)
    ) else 1


def feature_decomp_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    return 0 if _contains_text(requirements_file, REQUIREMENTS_MARKER) else 1


def uat_testcases_dependency_surfaces_present(workspace_root: Path) -> int:
    requirements_file = workspace_root / "specification" / "requirements" / "10-generated-bootstrap.md"
    return 0 if _contains_text(requirements_file, REQUIREMENTS_MARKER) else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="odd_sdlc.fd_checks")
    parser.add_argument(
        "check",
        choices=(
            "bootstrap-input-set-present",
            "product-dependency-surfaces-present",
            "goal-dependency-surfaces-present",
            "requirements-boundary-sources-present",
            "feature-decomp-dependency-surfaces-present",
            "uat-testcases-dependency-surfaces-present",
        ),
    )
    parser.add_argument("--workspace", default=".")
    args = parser.parse_args(argv)

    workspace_root = Path(args.workspace).resolve()
    if args.check == "bootstrap-input-set-present":
        return bootstrap_input_set_present(workspace_root)
    if args.check == "product-dependency-surfaces-present":
        return product_dependency_surfaces_present(workspace_root)
    if args.check == "goal-dependency-surfaces-present":
        return goal_dependency_surfaces_present(workspace_root)
    if args.check == "feature-decomp-dependency-surfaces-present":
        return feature_decomp_dependency_surfaces_present(workspace_root)
    if args.check == "uat-testcases-dependency-surfaces-present":
        return uat_testcases_dependency_surfaces_present(workspace_root)
    return requirements_boundary_sources_present(workspace_root)


if __name__ == "__main__":
    raise SystemExit(main())
