# Implements: REQ-F-ASSETMODEL-004
# Implements: REQ-F-ODDSDLC-002
# Implements: REQ-F-ODDSDLC-030
# Implements: REQ-F-ODDSDLC-031
"""Named function catalog for the retained odd_sdlc proving subset."""
from __future__ import annotations

from .domain_model import FunctionCatalogEntry


FUNCTION_CATALOG: tuple[FunctionCatalogEntry, ...] = (
    FunctionCatalogEntry(
        name="derive_intent_surface",
        intent="Derive or revise the intent surface from the bound bootstrap input set.",
        inputs=("input_set",),
        outputs=("intent_surface",),
        backing_graph_function="derive_intent_surface",
    ),
    FunctionCatalogEntry(
        name="derive_product_surface",
        intent="Derive or revise the product surface from the bound bootstrap input set and the current intent surface.",
        inputs=("input_set", "intent_surface"),
        outputs=("product_surface",),
        backing_graph_function="derive_product_surface",
    ),
    FunctionCatalogEntry(
        name="derive_goal_surface",
        intent="Derive or revise the goals surface from the bound bootstrap input set, the current intent surface, and the current product surface without dropping imported intent identifiers or inventing silent scope loss.",
        inputs=("input_set", "intent_surface", "product_surface"),
        outputs=("goal_surface",),
        backing_graph_function="derive_goal_surface",
    ),
    FunctionCatalogEntry(
        name="derive_requirement_surface",
        intent="Derive the requirement family surface from input, intent, product, and goals while carrying forward the full live requirement inventory into the current wave.",
        inputs=("input_set", "intent_surface", "product_surface", "goal_surface"),
        outputs=("requirement_surface",),
        backing_graph_function="derive_requirement_surface",
    ),
    FunctionCatalogEntry(
        name="derive_feature_decomp_surface",
        intent="Derive feature decomposition structure from the current requirement surface.",
        inputs=("requirement_surface",),
        outputs=("feature_decomp_surface",),
        backing_graph_function="derive_feature_decomp_surface",
    ),
    FunctionCatalogEntry(
        name="derive_uat_testcases_surface",
        intent="Derive operator-facing UAT testcase structure from the current requirement surface.",
        inputs=("requirement_surface",),
        outputs=("uat_testcases_surface",),
        backing_graph_function="derive_uat_testcases_surface",
    ),
    FunctionCatalogEntry(
        name="derive_design_surface",
        intent="Derive a generated design surface from the current requirement surface and feature decomposition.",
        inputs=("requirement_surface", "feature_decomp_surface"),
        outputs=("design_surface",),
        backing_graph_function="derive_design_surface",
    ),
    FunctionCatalogEntry(
        name="derive_scenario_surface",
        intent="Derive generated scenario bundles from the current requirement and design surfaces.",
        inputs=("requirement_surface", "design_surface"),
        outputs=("scenario_surface",),
        backing_graph_function="derive_scenario_surface",
    ),
    FunctionCatalogEntry(
        name="derive_implementation_design_surface",
        intent="Derive recursive implementation-SDLC design from the current design and scenario surfaces.",
        inputs=("design_surface", "scenario_surface"),
        outputs=("implementation_design_surface",),
        backing_graph_function="derive_implementation_design_surface",
    ),
    FunctionCatalogEntry(
        name="select_implementation_stack_profile",
        intent="Select the concrete implementation stack profile for the current generated implementation design surface.",
        inputs=("implementation_design_surface",),
        outputs=("implementation_stack_profile",),
        backing_graph_function="select_implementation_stack_profile",
    ),
    FunctionCatalogEntry(
        name="derive_implementation_module_surface",
        intent="Derive generated implementation module structure from the current implementation design and selected stack profile, including the requirement sets each module claims to realize.",
        inputs=("implementation_design_surface", "implementation_stack_profile"),
        outputs=("implementation_module_surface",),
        backing_graph_function="derive_implementation_module_surface",
    ),
    FunctionCatalogEntry(
        name="derive_code_surface",
        intent="Derive generated executable code from the current implementation module surface and selected implementation stack profile, with explicit Implements trace authority for every requirement claimed by the current implementation branch.",
        inputs=("implementation_module_surface", "implementation_stack_profile"),
        outputs=("code_surface",),
        backing_graph_function="derive_code_surface",
    ),
    FunctionCatalogEntry(
        name="derive_test_design_surface",
        intent="Derive recursive test-SDLC design from the current design and scenario surfaces.",
        inputs=("design_surface", "scenario_surface"),
        outputs=("test_design_surface",),
        backing_graph_function="derive_test_design_surface",
    ),
    FunctionCatalogEntry(
        name="select_test_stack_profile",
        intent="Select the concrete test stack profile for the current generated test design surface using the active implementation design and implementation stack truth.",
        inputs=("test_design_surface",),
        outputs=("test_stack_profile",),
        backing_graph_function="select_test_stack_profile",
    ),
    FunctionCatalogEntry(
        name="derive_test_module_surface",
        intent="Derive generated test module structure from the current test design, selected stack profile, and implementation module surface, including the planned requirement sets each generated developer-test lane is expected to validate.",
        inputs=("test_design_surface", "test_stack_profile"),
        outputs=("test_module_surface",),
        backing_graph_function="derive_test_module_surface",
    ),
    FunctionCatalogEntry(
        name="derive_test_run_archive_surface",
        intent="Derive governed archive-evidence design from the current test module surface and selected test stack profile, materializing governed developer-test source under the active code root before summarizing retained evidence.",
        inputs=("test_module_surface", "test_stack_profile"),
        outputs=("test_run_archive_surface",),
        backing_graph_function="derive_test_run_archive_surface",
    ),
    FunctionCatalogEntry(
        name="qualify_testcase_authority",
        intent="Qualify the current generated UAT testcase collection together with the generated scenario set as the authoritative testcase surface for downstream proof.",
        inputs=("uat_testcases_surface", "scenario_surface"),
        outputs=("testcase_authority_surface",),
        backing_graph_function="qualify_testcase_authority",
    ),
    FunctionCatalogEntry(
        name="prepare_release_surface",
        intent="Prepare a generated release readiness surface from the current requirements, design, scenarios, implementation code, testcase authority, and archived test evidence.",
        inputs=("requirement_surface", "design_surface", "scenario_surface", "code_surface", "testcase_authority_surface", "test_run_archive_surface"),
        outputs=("release_surface",),
        backing_graph_function="prepare_release_surface",
    ),
    FunctionCatalogEntry(
        name="prepare_build_execution_surface",
        intent="Prepare a command-side build transition surface from the current release position and the declared build execution substrate contract.",
        inputs=("release_surface",),
        outputs=("build_execution_surface",),
        backing_graph_function="prepare_build_execution_surface",
    ),
    FunctionCatalogEntry(
        name="derive_build_execution_result_surface",
        intent="Admit returned build execution result or pending external build state as a governed result surface.",
        inputs=("build_execution_surface",),
        outputs=("build_execution_result_surface",),
        backing_graph_function="derive_build_execution_result_surface",
    ),
    FunctionCatalogEntry(
        name="prepare_test_execution_surface",
        intent="Prepare a command-side test execution transition surface from the current release position and the declared test execution substrate contract.",
        inputs=("release_surface",),
        outputs=("test_execution_surface",),
        backing_graph_function="prepare_test_execution_surface",
    ),
    FunctionCatalogEntry(
        name="derive_test_execution_result_surface",
        intent="Admit returned test execution evidence from the archived governed test lane as a distinct operational result surface.",
        inputs=("test_execution_surface", "test_run_archive_surface"),
        outputs=("test_execution_result_surface",),
        backing_graph_function="derive_test_execution_result_surface",
    ),
    FunctionCatalogEntry(
        name="prepare_deployment_surface",
        intent="Prepare a command-side deployment transition surface from the current qualified release position and declared deployment substrate contract.",
        inputs=("release_surface",),
        outputs=("deployment_surface",),
        backing_graph_function="prepare_deployment_surface",
    ),
    FunctionCatalogEntry(
        name="derive_deployment_result_surface",
        intent="Admit returned deployment result or explicit pending external completion state as a governed deployment result surface.",
        inputs=("deployment_surface",),
        outputs=("deployment_result_surface",),
        backing_graph_function="derive_deployment_result_surface",
    ),
    FunctionCatalogEntry(
        name="derive_deployed_environment_surface",
        intent="Project the current deployed-environment read model from the admitted deployment result surface.",
        inputs=("deployment_result_surface",),
        outputs=("deployed_environment_surface",),
        backing_graph_function="derive_deployed_environment_surface",
    ),
    FunctionCatalogEntry(
        name="derive_runtime_observation_surface",
        intent="Bind returned runtime or execution evidence back into the worksite as a governed observation surface distinct from both deployment command intent and current projected state.",
        inputs=("deployment_result_surface", "test_run_archive_surface"),
        outputs=("runtime_observation_surface",),
        backing_graph_function="derive_runtime_observation_surface",
    ),
    FunctionCatalogEntry(
        name="derive_retrofit_plan_surface",
        intent="Plan the next bounded retrofit wave from returned runtime observation and the current release position.",
        inputs=("runtime_observation_surface", "release_surface"),
        outputs=("retrofit_plan_surface",),
        backing_graph_function="derive_retrofit_plan_surface",
    ),
    FunctionCatalogEntry(
        name="review_subject_consensus_round",
        intent="Publish one reusable subject-review consensus round over subject, assessment, decision, and reviewed-subject roles.",
        inputs=("subject_surface",),
        outputs=("reviewed_subject_surface",),
        backing_graph_function="review_subject_consensus_round",
    ),
    FunctionCatalogEntry(
        name="review_subject_by_consensus",
        intent="Publish the reusable higher-order subject consensus plugin with explicit stage and policy metadata.",
        inputs=("subject_surface",),
        outputs=("reviewed_subject_surface",),
        backing_graph_function="review_subject_by_consensus",
    ),
    FunctionCatalogEntry(
        name="review_design_consensus_round",
        intent="Bind the reusable consensus round to odd_sdlc design review subjects.",
        inputs=("design_surface",),
        outputs=("reviewed_design_surface",),
        backing_graph_function="review_design_consensus_round",
    ),
    FunctionCatalogEntry(
        name="review_design_by_consensus",
        intent="Bind the reusable higher-order subject consensus plugin to odd_sdlc design review subjects.",
        inputs=("design_surface",),
        outputs=("reviewed_design_surface",),
        backing_graph_function="review_design_by_consensus",
    ),
    FunctionCatalogEntry(
        name="review_comment_consensus_round",
        intent="Bind the reusable consensus round to odd_sdlc comment-review subjects.",
        inputs=("comment_review_subject_surface",),
        outputs=("reviewed_comment_surface",),
        backing_graph_function="review_comment_consensus_round",
    ),
    FunctionCatalogEntry(
        name="review_comment_by_consensus",
        intent="Bind the reusable higher-order subject consensus plugin to odd_sdlc comment-review subjects.",
        inputs=("comment_review_subject_surface",),
        outputs=("reviewed_comment_surface",),
        backing_graph_function="review_comment_by_consensus",
    ),
)
