# Implements: REQ-F-ASSETMODEL-001
# Implements: REQ-F-ASSETMODEL-003
# Implements: REQ-F-ASSETMODEL-005
# Implements: REQ-F-ODDSDLC-020
# Implements: REQ-F-ODDSDLC-027
# Implements: REQ-F-ODDSDLC-029
# Implements: REQ-F-ODDSDLC-032
"""Active odd_sdlc asset inventory and bindings for software-domain workspaces."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path
from xml.etree import ElementTree

from .asset_types import ASSET_TYPES
from .ambiguity import AMBIGUITY_REGISTER_PATH, AMBIGUITY_REGISTER_KIND
from .domain_model import (
    Asset,
    AssetCheckpoint,
    AssetCollection,
    AssetNodeBinding,
    AssetProvenance,
    relative_file_uri,
)
from .project_profile import (
    DEFAULT_PROVING_CODE_RELATIVE_PATH,
    ProjectProfile,
    load_project_profile,
    profile_design_relative_path,
    profile_test_env_relative_path,
    profile_test_env_tests_relative_path,
    realization_candidates_for_selected_root,
)
from .traceability import (
    REQUIREMENT_CLOSURE_REGISTER_KIND,
    REQUIREMENT_CLOSURE_REGISTER_PATH,
)


ASSET_PATHS: tuple[tuple[str, str], ...] = (
    ("intent_surface", "specification/INTENT.md"),
    ("product_surface", "specification/PRODUCT.md"),
    ("goal_surface", "specification/GOALS.md"),
    ("ambiguity_register_surface", AMBIGUITY_REGISTER_PATH.as_posix()),
    ("requirement_closure_register_surface", REQUIREMENT_CLOSURE_REGISTER_PATH.as_posix()),
    ("requirement_surface", "specification/requirements"),
    ("feature_decomp_surface", "build_tenants/<tenant>/design/20-generated-feature-decomp.md"),
    ("uat_testcases_surface", "specification/scenarios/20-generated-uat-testcases.md"),
    ("design_surface", "build_tenants/<tenant>/design/30-generated-odd-design.md"),
    ("review_assessment_surface", "build_tenants/<tenant>/design/35-generated-review-assessments.md"),
    ("consensus_decision_surface", "build_tenants/<tenant>/design/35-generated-consensus-decision.md"),
    ("reviewed_design_surface", "build_tenants/<tenant>/design/35-reviewed-odd-design.md"),
    ("testcase_authority_surface", "specification/scenarios/30-generated-testcase-authority.md"),
    ("scenario_surface", "specification/scenarios/40-generated-scenarios.md"),
    ("implementation_design_surface", "build_tenants/<tenant>/design/40-generated-implementation-design.md"),
    ("implementation_stack_profile", "build_tenants/<tenant>/design/40-generated-implementation-stack.md"),
    ("implementation_module_surface", "build_tenants/<tenant>/design/40-generated-implementation-modules.md"),
    ("code_surface", DEFAULT_PROVING_CODE_RELATIVE_PATH),
    ("test_design_surface", "build_tenants/<tenant>/design/40-generated-test-design.md"),
    ("test_stack_profile", "build_tenants/<tenant>/test_env/40-generated-test-stack.md"),
    ("test_module_surface", "build_tenants/<tenant>/test_env/tests/40-generated-test-modules.md"),
    ("test_run_archive_surface", "build_tenants/<tenant>/test_env/50-generated-run-archive.md"),
    ("release_surface", "docs/40-generated-release.md"),
    ("build_execution_surface", "docs/45-generated-build-execution.md"),
    ("build_execution_result_surface", "docs/46-generated-build-execution-result.md"),
    ("test_execution_surface", "docs/47-generated-test-execution.md"),
    ("test_execution_result_surface", "docs/48-generated-test-execution-result.md"),
    ("deployment_surface", "docs/50-generated-deployment.md"),
    ("deployment_result_surface", "docs/55-generated-deployment-result.md"),
    ("deployed_environment_surface", "docs/56-generated-deployed-environment.md"),
    ("runtime_observation_surface", "docs/60-generated-runtime-observation.md"),
    ("retrofit_plan_surface", "build_tenants/<tenant>/design/60-generated-retrofit-plan.md"),
)
ASSET_RELATIVE_PATHS = dict(ASSET_PATHS)
DYNAMIC_TENANT_ASSET_IDS = {
    "feature_decomp_surface",
    "design_surface",
    "review_assessment_surface",
    "consensus_decision_surface",
    "reviewed_design_surface",
    "implementation_design_surface",
    "implementation_stack_profile",
    "implementation_module_surface",
    "test_design_surface",
    "test_stack_profile",
    "test_module_surface",
    "test_run_archive_surface",
    "retrofit_plan_surface",
}
ASSET_PRIMARY_MEMBERS: dict[str, tuple[str, ...]] = {
    "requirement_surface": ("10-generated-bootstrap.md",),
}
ASSET_MARKER_MEMBERS: dict[str, tuple[str, ...]] = {
    "code_surface": ("__init__.py",),
}
ASSET_MARKERS: dict[str, str] = {
    "intent_surface": "This intent surface is regenerated by the bounded odd_sdlc constructor turn.",
    "product_surface": "This product surface is regenerated by the bounded odd_sdlc constructor turn.",
    "goal_surface": "These goals are regenerated by the bounded odd_sdlc constructor turn.",
    "ambiguity_register_surface": f'"register_kind": "{AMBIGUITY_REGISTER_KIND}"',
    "requirement_closure_register_surface": f'"register_kind": "{REQUIREMENT_CLOSURE_REGISTER_KIND}"',
    "requirement_surface": "This requirement surface is regenerated by the bounded odd_sdlc constructor turn.",
    "feature_decomp_surface": "This feature decomposition surface is regenerated by the bounded odd_sdlc constructor turn.",
    "uat_testcases_surface": "This UAT testcase surface is regenerated by the bounded odd_sdlc constructor turn.",
    "design_surface": "This design surface is regenerated by the bounded odd_sdlc constructor turn.",
    "review_assessment_surface": "This review assessment surface is regenerated by the bounded odd_sdlc constructor turn.",
    "consensus_decision_surface": "This consensus decision surface is regenerated by the bounded odd_sdlc constructor turn.",
    "reviewed_design_surface": "This reviewed design surface is regenerated by the bounded odd_sdlc constructor turn.",
    "testcase_authority_surface": "This testcase authority surface is regenerated by the bounded odd_sdlc constructor turn.",
    "scenario_surface": "This scenario surface is regenerated by the bounded odd_sdlc constructor turn.",
    "implementation_design_surface": "This implementation design surface is regenerated by the bounded odd_sdlc constructor turn.",
    "implementation_stack_profile": "This implementation stack profile is regenerated by the bounded odd_sdlc constructor turn.",
    "implementation_module_surface": "This implementation module surface is regenerated by the bounded odd_sdlc constructor turn.",
    "code_surface": "This code surface is regenerated by the bounded odd_sdlc constructor turn.",
    "test_design_surface": "This test design surface is regenerated by the bounded odd_sdlc constructor turn.",
    "test_stack_profile": "This test stack profile is regenerated by the bounded odd_sdlc constructor turn.",
    "test_module_surface": "This test module surface is regenerated by the bounded odd_sdlc constructor turn.",
    "test_run_archive_surface": "This test run archive surface is regenerated by the bounded odd_sdlc constructor turn.",
    "release_surface": "This release surface is regenerated by the bounded odd_sdlc constructor turn.",
    "build_execution_surface": "This build execution surface is regenerated by the bounded odd_sdlc constructor turn.",
    "build_execution_result_surface": "This build execution result surface is regenerated by the bounded odd_sdlc constructor turn.",
    "test_execution_surface": "This test execution surface is regenerated by the bounded odd_sdlc constructor turn.",
    "test_execution_result_surface": "This test execution result surface is regenerated by the bounded odd_sdlc constructor turn.",
    "deployment_surface": "This deployment surface is regenerated by the bounded odd_sdlc constructor turn.",
    "deployment_result_surface": "This deployment result surface is regenerated by the bounded odd_sdlc constructor turn.",
    "deployed_environment_surface": "This deployed environment surface is regenerated by the bounded odd_sdlc constructor turn.",
    "runtime_observation_surface": "This runtime observation surface is regenerated by the bounded odd_sdlc constructor turn.",
    "retrofit_plan_surface": "This retrofit plan surface is regenerated by the bounded odd_sdlc constructor turn.",
}
CODE_SURFACE_PREFIXES: tuple[tuple[str, str], ...] = (
    ("__init__.py", '"""Generated odd_sdlc proving-subset implementation package."""'),
    ("__main__.py", '"""Package entry point for the generated odd_sdlc proving application."""'),
    ("app.py", '"""Generated hello-world application for the odd_sdlc proving subset."""'),
    ("workflow.py", '"""Generated implementation workflow helpers for the odd_sdlc proving subset."""'),
)
CODE_SURFACE_PREFIX_BY_PATH = dict(CODE_SURFACE_PREFIXES)
AUTHORITATIVE_FILE_HEADING_PREFIXES: dict[str, tuple[str, ...]] = {
    "intent_surface": ("# Intent", "# Project Intent"),
    "product_surface": ("# Product",),
    "goal_surface": ("# Goals",),
}
TOPOLOGY_GUARDED_ASSETS = {
    "code_surface",
    "test_run_archive_surface",
    "release_surface",
    "build_execution_surface",
    "build_execution_result_surface",
    "test_execution_surface",
    "test_execution_result_surface",
    "deployment_surface",
    "deployment_result_surface",
    "deployed_environment_surface",
    "runtime_observation_surface",
    "retrofit_plan_surface",
}
GOVERNANCE_TOP_LEVEL_NAMES = {
    ".ai-workspace",
    ".genesis",
    ".git",
    ".odd_sdlc",
    "__pycache__",
    "build_tenants",
    "docs",
    "specification",
}
IGNORED_REALIZATION_DIR_NAMES = {
    ".ai-workspace",
    ".genesis",
    ".git",
    "__pycache__",
    "node_modules",
}
SOFTWARE_BUILD_MARKERS = (
    "build.sbt",
    "build.gradle",
    "build.gradle.kts",
    "Cargo.toml",
    "go.mod",
    "package.json",
    "pom.xml",
    "pyproject.toml",
    "setup.py",
)
SOFTWARE_SOURCE_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".go",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".php",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".swift",
    ".ts",
    ".tsx",
}
TEST_REPORT_PATTERNS = (
    "**/TEST-*.xml",
    "**/junit*.xml",
    "**/surefire-reports/*.xml",
    "**/test-reports/*.xml",
)

INPUT_SET_ASSET_IDS: tuple[str, ...] = (
    "intent_surface",
    "product_surface",
    "goal_surface",
)

NODE_ASSET_TYPES = {
    "intent_surface": "intent_doc",
    "product_surface": "product_doc",
    "goal_surface": "goal_surface",
    "ambiguity_register_surface": "ambiguity_register_surface",
    "requirement_closure_register_surface": "requirement_closure_register_surface",
    "requirement_surface": "requirement_surface",
    "feature_decomp_surface": "feature_decomp_surface",
    "uat_testcases_surface": "uat_testcases_surface",
    "design_surface": "design_surface",
    "review_assessment_surface": "review_assessment_surface",
    "consensus_decision_surface": "consensus_decision_surface",
    "reviewed_design_surface": "reviewed_design_surface",
    "testcase_authority_surface": "testcase_authority_surface",
    "scenario_surface": "scenario_surface",
    "implementation_design_surface": "implementation_design_surface",
    "implementation_stack_profile": "implementation_stack_profile",
    "implementation_module_surface": "implementation_module_surface",
    "code_surface": "code_surface",
    "test_design_surface": "test_design_surface",
    "test_stack_profile": "test_stack_profile",
    "test_module_surface": "test_module_surface",
    "test_run_archive_surface": "test_run_archive_surface",
    "release_surface": "release_surface",
    "build_execution_surface": "work_request_surface",
    "build_execution_result_surface": "operational_evidence_surface",
    "test_execution_surface": "work_request_surface",
    "test_execution_result_surface": "operational_evidence_surface",
    "deployment_surface": "work_request_surface",
    "deployment_result_surface": "operational_evidence_surface",
    "deployed_environment_surface": "deployment_record_surface",
    "runtime_observation_surface": "runtime_observation_surface",
    "retrofit_plan_surface": "maintenance_plan_surface",
}


@dataclass(frozen=True)
class GeneratedAssetContract:
    asset_id: str
    materialization_kind: str
    heading_prefix: str | None = None
    required_files: tuple[str, ...] = ()
    required_member_prefixes: tuple[tuple[str, str], ...] = ()

    def to_dict(self) -> dict[str, object]:
        return {
            "asset_id": self.asset_id,
            "materialization_kind": self.materialization_kind,
            "heading_prefix": self.heading_prefix,
            "required_files": list(self.required_files),
            "required_member_prefixes": [
                {"path": relative_path, "prefix": prefix}
                for relative_path, prefix in self.required_member_prefixes
            ],
        }


GENERATED_ASSET_CONTRACTS: dict[str, GeneratedAssetContract] = {
    "intent_surface": GeneratedAssetContract("intent_surface", "file", heading_prefix="# Intent"),
    "product_surface": GeneratedAssetContract("product_surface", "file", heading_prefix="# Product"),
    "goal_surface": GeneratedAssetContract("goal_surface", "file", heading_prefix="# Goals"),
    "ambiguity_register_surface": GeneratedAssetContract(
        "ambiguity_register_surface",
        "file",
    ),
    "requirement_closure_register_surface": GeneratedAssetContract(
        "requirement_closure_register_surface",
        "file",
    ),
    "requirement_surface": GeneratedAssetContract(
        "requirement_surface",
        "file",
        heading_prefix="# Generated Bootstrap Requirements",
    ),
    "feature_decomp_surface": GeneratedAssetContract(
        "feature_decomp_surface",
        "file",
        heading_prefix="# Generated Feature Decomposition",
    ),
    "uat_testcases_surface": GeneratedAssetContract(
        "uat_testcases_surface",
        "file",
        heading_prefix="# Generated UAT Testcases",
    ),
    "design_surface": GeneratedAssetContract(
        "design_surface",
        "file",
        heading_prefix="# Generated odd_sdlc Design",
    ),
    "review_assessment_surface": GeneratedAssetContract(
        "review_assessment_surface",
        "file",
        heading_prefix="# Generated Review Assessments",
    ),
    "consensus_decision_surface": GeneratedAssetContract(
        "consensus_decision_surface",
        "file",
        heading_prefix="# Generated Consensus Decision",
    ),
    "reviewed_design_surface": GeneratedAssetContract(
        "reviewed_design_surface",
        "file",
        heading_prefix="# Reviewed odd_sdlc Design",
    ),
    "testcase_authority_surface": GeneratedAssetContract(
        "testcase_authority_surface",
        "file",
        heading_prefix="# Generated Testcase Authority",
    ),
    "scenario_surface": GeneratedAssetContract(
        "scenario_surface",
        "file",
        heading_prefix="# Generated Scenarios",
    ),
    "implementation_design_surface": GeneratedAssetContract(
        "implementation_design_surface",
        "file",
        heading_prefix="# Generated Implementation Design",
    ),
    "implementation_stack_profile": GeneratedAssetContract(
        "implementation_stack_profile",
        "file",
        heading_prefix="# Generated Implementation Stack Profile",
    ),
    "implementation_module_surface": GeneratedAssetContract(
        "implementation_module_surface",
        "file",
        heading_prefix="# Generated Implementation Modules",
    ),
    "code_surface": GeneratedAssetContract(
        "code_surface",
        "directory",
        required_files=("__init__.py", "__main__.py", "app.py", "workflow.py"),
        required_member_prefixes=CODE_SURFACE_PREFIXES,
    ),
    "test_design_surface": GeneratedAssetContract(
        "test_design_surface",
        "file",
        heading_prefix="# Generated Test Design",
    ),
    "test_stack_profile": GeneratedAssetContract(
        "test_stack_profile",
        "file",
        heading_prefix="# Generated Test Stack Profile",
    ),
    "test_module_surface": GeneratedAssetContract(
        "test_module_surface",
        "file",
        heading_prefix="# Generated Test Modules",
    ),
    "test_run_archive_surface": GeneratedAssetContract(
        "test_run_archive_surface",
        "file",
        heading_prefix="# Generated Test Run Archive",
    ),
    "release_surface": GeneratedAssetContract(
        "release_surface",
        "file",
        heading_prefix="# Generated Release Surface",
    ),
    "build_execution_surface": GeneratedAssetContract(
        "build_execution_surface",
        "file",
        heading_prefix="# Generated Build Execution Surface",
    ),
    "build_execution_result_surface": GeneratedAssetContract(
        "build_execution_result_surface",
        "file",
        heading_prefix="# Generated Build Execution Result Surface",
    ),
    "test_execution_surface": GeneratedAssetContract(
        "test_execution_surface",
        "file",
        heading_prefix="# Generated Test Execution Surface",
    ),
    "test_execution_result_surface": GeneratedAssetContract(
        "test_execution_result_surface",
        "file",
        heading_prefix="# Generated Test Execution Result Surface",
    ),
    "deployment_surface": GeneratedAssetContract(
        "deployment_surface",
        "file",
        heading_prefix="# Generated Deployment Surface",
    ),
    "deployment_result_surface": GeneratedAssetContract(
        "deployment_result_surface",
        "file",
        heading_prefix="# Generated Deployment Result Surface",
    ),
    "deployed_environment_surface": GeneratedAssetContract(
        "deployed_environment_surface",
        "file",
        heading_prefix="# Generated Deployed Environment Surface",
    ),
    "runtime_observation_surface": GeneratedAssetContract(
        "runtime_observation_surface",
        "file",
        heading_prefix="# Generated Runtime Observation Surface",
    ),
    "retrofit_plan_surface": GeneratedAssetContract(
        "retrofit_plan_surface",
        "file",
        heading_prefix="# Generated Retrofit Plan",
    ),
}


def asset_relative_path(asset_id: str) -> str:
    try:
        return ASSET_RELATIVE_PATHS[asset_id]
    except KeyError as exc:
        raise ValueError(f"Unsupported asset_id {asset_id!r}") from exc


def _tenant_asset_relative_path(workspace_root: Path, asset_id: str) -> str:
    profile = load_project_profile(workspace_root)
    if asset_id == "feature_decomp_surface":
        return profile_design_relative_path(profile, "20-generated-feature-decomp.md")
    if asset_id == "design_surface":
        return profile_design_relative_path(profile, "30-generated-odd-design.md")
    if asset_id == "review_assessment_surface":
        return profile_design_relative_path(profile, "35-generated-review-assessments.md")
    if asset_id == "consensus_decision_surface":
        return profile_design_relative_path(profile, "35-generated-consensus-decision.md")
    if asset_id == "reviewed_design_surface":
        return profile_design_relative_path(profile, "35-reviewed-odd-design.md")
    if asset_id == "implementation_design_surface":
        return profile_design_relative_path(profile, "40-generated-implementation-design.md")
    if asset_id == "implementation_stack_profile":
        return profile_design_relative_path(profile, "40-generated-implementation-stack.md")
    if asset_id == "implementation_module_surface":
        return profile_design_relative_path(profile, "40-generated-implementation-modules.md")
    if asset_id == "test_design_surface":
        return profile_design_relative_path(profile, "40-generated-test-design.md")
    if asset_id == "test_stack_profile":
        return profile_test_env_relative_path(profile, "40-generated-test-stack.md")
    if asset_id == "test_module_surface":
        return profile_test_env_tests_relative_path(profile, "40-generated-test-modules.md")
    if asset_id == "test_run_archive_surface":
        return profile_test_env_relative_path(profile, "50-generated-run-archive.md")
    if asset_id == "retrofit_plan_surface":
        return profile_design_relative_path(profile, "60-generated-retrofit-plan.md")
    raise ValueError(f"Unsupported dynamic tenant asset_id {asset_id!r}")


def resolved_asset_relative_path(workspace_root: Path, asset_id: str) -> str:
    if asset_id in DYNAMIC_TENANT_ASSET_IDS:
        return _tenant_asset_relative_path(workspace_root, asset_id)
    if asset_id != "code_surface":
        return asset_relative_path(asset_id)
    return load_project_profile(workspace_root).code_relative_path()


def asset_path(workspace_root: Path, asset_id: str) -> Path:
    return workspace_root / resolved_asset_relative_path(workspace_root, asset_id)


def asset_materialization_path(workspace_root: Path, asset_id: str) -> Path:
    path = asset_path(workspace_root, asset_id)
    primary_member = ASSET_PRIMARY_MEMBERS.get(asset_id)
    if primary_member is None:
        return path
    return path.joinpath(*primary_member)


def asset_marker_path(workspace_root: Path, asset_id: str) -> Path:
    path = asset_materialization_path(workspace_root, asset_id)
    marker_member = ASSET_MARKER_MEMBERS.get(asset_id)
    if marker_member is None:
        return path
    return asset_path(workspace_root, asset_id).joinpath(*marker_member)


def asset_declared_type(asset_id: str) -> str:
    try:
        return NODE_ASSET_TYPES[asset_id]
    except KeyError as exc:
        raise ValueError(f"Unsupported asset_id {asset_id!r}") from exc


def asset_marker(asset_id: str) -> str:
    try:
        return ASSET_MARKERS[asset_id]
    except KeyError as exc:
        raise ValueError(f"Unsupported asset_id {asset_id!r}") from exc


def _resolved_generated_asset_contract(
    workspace_root: Path,
    asset_id: str,
) -> GeneratedAssetContract:
    if asset_id == "code_surface":
        profile = load_project_profile(workspace_root)
        if profile.realization_mode in {"selected_output_tree", "planned_output_tree"}:
            return GeneratedAssetContract("code_surface", "directory")
    return generated_asset_contract(asset_id)


def generated_asset_contract(asset_id: str) -> GeneratedAssetContract:
    try:
        return GENERATED_ASSET_CONTRACTS[asset_id]
    except KeyError as exc:
        raise ValueError(f"Unsupported asset_id {asset_id!r}") from exc


def generated_asset_heading(asset_id: str) -> str:
    heading_prefix = generated_asset_contract(asset_id).heading_prefix
    if heading_prefix is None:
        raise ValueError(f"Asset {asset_id!r} does not declare a generated heading prefix")
    return heading_prefix


def code_surface_member_prefix(relative_path: str) -> str:
    try:
        return CODE_SURFACE_PREFIX_BY_PATH[relative_path]
    except KeyError as exc:
        raise ValueError(f"Unsupported code surface member {relative_path!r}") from exc


def _path_kind(path: Path) -> str:
    if not path.exists():
        return "missing"
    if path.is_dir():
        return "directory"
    return "file"


def _text_contains(path: Path, needle: str) -> bool:
    return path.exists() and path.is_file() and needle in path.read_text(encoding="utf-8")


def _text_startswith(path: Path, prefix: str) -> bool:
    return path.exists() and path.is_file() and path.read_text(encoding="utf-8").startswith(prefix)


def _text_startswith_any(path: Path, prefixes: tuple[str, ...]) -> bool:
    if not path.exists() or not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    return any(text.startswith(prefix) for prefix in prefixes)


def _is_realization_file(path: Path, *, root: Path) -> bool:
    relative_parts = path.relative_to(root).parts
    return (
        path.suffix in SOFTWARE_SOURCE_SUFFIXES
        and not any(part in IGNORED_REALIZATION_DIR_NAMES for part in relative_parts)
    )


def _test_report_count(root: Path) -> int:
    seen: set[Path] = set()
    for pattern in TEST_REPORT_PATTERNS:
        for path in root.glob(pattern):
            if path.is_file():
                seen.add(path)
    return len(seen)


def summarize_code_surface(workspace_root: Path) -> dict[str, object]:
    code_root = asset_path(workspace_root, "code_surface")
    build_markers = [marker for marker in SOFTWARE_BUILD_MARKERS if (code_root / marker).is_file()]
    source_files = [
        path
        for path in code_root.rglob("*")
        if path.is_file() and _is_realization_file(path, root=code_root)
    ] if code_root.exists() and code_root.is_dir() else []
    test_source_files = [
        path
        for path in source_files
        if "test" in {part.lower() for part in path.relative_to(code_root).parts}
    ]
    return {
        "relative_path": resolved_asset_relative_path(workspace_root, "code_surface"),
        "build_markers": build_markers,
        "source_file_count": len(source_files),
        "test_source_file_count": len(test_source_files),
        "test_report_file_count": _test_report_count(code_root) if code_root.exists() and code_root.is_dir() else 0,
    }


def summarize_test_evidence(workspace_root: Path) -> dict[str, object]:
    code_root = asset_path(workspace_root, "code_surface")
    profile = load_project_profile(workspace_root)
    report_files: list[Path] = []
    if code_root.exists() and code_root.is_dir():
        seen: set[Path] = set()
        for pattern in TEST_REPORT_PATTERNS:
            for path in code_root.glob(pattern):
                if path.is_file() and path not in seen:
                    seen.add(path)
                    report_files.append(path)
    foreign_report_files: list[Path] = []
    seen_foreign: set[Path] = set()
    selected_code_root_name = _selected_code_root_name(workspace_root)
    for child in sorted(workspace_root.iterdir()):
        if not child.is_dir() or child.name in GOVERNANCE_TOP_LEVEL_NAMES or child.name == selected_code_root_name:
            continue
        for pattern in TEST_REPORT_PATTERNS:
            for path in child.glob(pattern):
                if path.is_file() and path not in seen_foreign:
                    seen_foreign.add(path)
                    foreign_report_files.append(path)
    active_build_tenant_root = _selected_build_tenant_root(workspace_root)
    build_tenants_root = workspace_root / "build_tenants"
    if build_tenants_root.exists() and build_tenants_root.is_dir():
        for tenant_root in sorted(build_tenants_root.iterdir()):
            if not tenant_root.is_dir():
                continue
            if active_build_tenant_root is not None and tenant_root == active_build_tenant_root:
                continue
            for pattern in TEST_REPORT_PATTERNS:
                for path in tenant_root.glob(pattern):
                    if path.is_file() and path not in seen_foreign:
                        seen_foreign.add(path)
                        foreign_report_files.append(path)
    tests = 0
    failures = 0
    errors = 0
    skipped = 0
    parsed_reports = 0
    for report in report_files:
        try:
            root = ElementTree.fromstring(report.read_text(encoding="utf-8"))
        except Exception:
            continue
        suites = [root] if root.tag == "testsuite" else list(root.findall(".//testsuite"))
        if not suites:
            continue
        parsed_reports += 1
        for suite in suites:
            tests += int(suite.attrib.get("tests", "0") or "0")
            failures += int(suite.attrib.get("failures", "0") or "0")
            errors += int(suite.attrib.get("errors", "0") or "0")
            skipped += int(suite.attrib.get("skipped", "0") or "0")
    report_paths = [
        path.relative_to(workspace_root).as_posix()
        for path in sorted(report_files)
    ]
    ungoverned_report_paths = [
        path.relative_to(workspace_root).as_posix()
        for path in sorted((*report_files, *foreign_report_files))
    ]
    if not profile.has_test_execution_capability():
        return {
            "report_file_count": 0,
            "parsed_report_count": 0,
            "tests": 0,
            "failures": 0,
            "errors": 0,
            "skipped": 0,
            "report_paths": [],
            "ungoverned_report_file_count": len(ungoverned_report_paths),
            "ungoverned_report_paths": ungoverned_report_paths,
        }
    return {
        "report_file_count": len(report_files),
        "parsed_report_count": parsed_reports,
        "tests": tests,
        "failures": failures,
        "errors": errors,
        "skipped": skipped,
        "report_paths": report_paths,
        "ungoverned_report_file_count": len(foreign_report_files),
        "ungoverned_report_paths": [
            path.relative_to(workspace_root).as_posix()
            for path in sorted(foreign_report_files)
        ],
    }


def _selected_code_root_name(workspace_root: Path) -> str | None:
    selected = asset_path(workspace_root, "code_surface")
    try:
        relative = selected.relative_to(workspace_root)
    except ValueError:
        return None
    return relative.parts[0] if relative.parts else None


def _selected_build_tenant_root(workspace_root: Path) -> Path | None:
    selected = asset_path(workspace_root, "code_surface")
    try:
        relative = selected.relative_to(workspace_root)
    except ValueError:
        return None
    if len(relative.parts) >= 2 and relative.parts[0] == "build_tenants":
        return workspace_root / relative.parts[0] / relative.parts[1]
    return None


def foreign_realization_candidates(workspace_root: Path) -> list[dict[str, object]]:
    return realization_candidates_for_selected_root(workspace_root)


def assess_realization_topology(workspace_root: Path) -> dict[str, object]:
    governed_code_path = asset_path(workspace_root, "code_surface")
    profile = load_project_profile(workspace_root)
    candidates = foreign_realization_candidates(workspace_root)
    return {
        "governed_code_relative_path": resolved_asset_relative_path(workspace_root, "code_surface"),
        "governed_code_path": str(governed_code_path),
        "project_profile": profile.to_dict(),
        "foreign_realization_candidates": candidates,
        "topology_diverged": bool(candidates),
    }


def assess_generated_asset_contract(workspace_root: Path, asset_id: str) -> dict[str, object]:
    contract = _resolved_generated_asset_contract(workspace_root, asset_id)
    project_profile = load_project_profile(workspace_root)
    root_path = asset_path(workspace_root, asset_id)
    materialization_path = asset_materialization_path(workspace_root, asset_id)
    marker_path = asset_marker_path(workspace_root, asset_id)
    marker_text = asset_marker(asset_id)

    heading_matches = True
    if contract.heading_prefix is not None:
        if asset_id in AUTHORITATIVE_FILE_HEADING_PREFIXES:
            heading_matches = _text_startswith_any(materialization_path, AUTHORITATIVE_FILE_HEADING_PREFIXES[asset_id])
        else:
            heading_matches = _text_startswith(materialization_path, contract.heading_prefix)

    missing_files = [
        relative_path
        for relative_path in contract.required_files
        if not (materialization_path / relative_path).is_file()
    ]
    member_prefix_failures = [
        {
            "path": relative_path,
            "expected_prefix": prefix,
        }
        for relative_path, prefix in contract.required_member_prefixes
        if not _text_startswith(materialization_path / relative_path, prefix)
    ]

    materialization_kind_actual = _path_kind(materialization_path)
    marker_present = _text_contains(marker_path, marker_text)
    code_summary: dict[str, object] | None = None
    adopted_authority = False
    if asset_id in AUTHORITATIVE_FILE_HEADING_PREFIXES and materialization_kind_actual == "file" and heading_matches:
        text = materialization_path.read_text(encoding="utf-8").strip()
        adopted_authority = bool(text)
        marker_present = marker_present or adopted_authority
    if asset_id == "code_surface" and project_profile.realization_mode in {"selected_output_tree", "planned_output_tree"}:
        code_summary = summarize_code_surface(workspace_root)
        marker_present = bool(code_summary["build_markers"]) or int(code_summary["source_file_count"]) > 0
    topology_report = assess_realization_topology(workspace_root)
    topology_guard_applied = asset_id in TOPOLOGY_GUARDED_ASSETS
    topology_guard_passed = not topology_guard_applied or not topology_report["topology_diverged"]
    contract_satisfied = (
        materialization_kind_actual == contract.materialization_kind
        and marker_present
        and heading_matches
        and not missing_files
        and not member_prefix_failures
        and topology_guard_passed
    )
    return {
        "asset_id": asset_id,
        "relative_path": resolved_asset_relative_path(workspace_root, asset_id),
        "root_path": str(root_path),
        "root_exists": root_path.exists(),
        "materialization_path": str(materialization_path),
        "materialization_kind_expected": contract.materialization_kind,
        "materialization_kind_actual": materialization_kind_actual,
        "exists": materialization_path.exists(),
        "marker_path": str(marker_path),
        "marker_present": marker_present,
        "heading_prefix": contract.heading_prefix,
        "heading_matches": heading_matches,
        "required_files": list(contract.required_files),
        "missing_files": missing_files,
        "required_member_prefixes": [
            {"path": relative_path, "prefix": prefix}
            for relative_path, prefix in contract.required_member_prefixes
        ],
        "member_prefix_failures": member_prefix_failures,
        "topology_guard_applied": topology_guard_applied,
        "topology_guard_passed": topology_guard_passed,
        "foreign_realization_candidates": topology_report["foreign_realization_candidates"],
        "project_profile": project_profile.to_dict(),
        "code_surface_summary": code_summary,
        "adopted_authority": adopted_authority,
        "contract": contract.to_dict(),
        "contract_satisfied": contract_satisfied,
    }


def _digest_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _digest_directory(path: Path) -> str:
    digest = hashlib.sha256()
    for child in sorted(item for item in path.rglob("*") if item.is_file()):
        digest.update(child.relative_to(path).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(_digest_file(child).encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def _directory_size(path: Path) -> int:
    return sum(child.stat().st_size for child in path.rglob("*") if child.is_file())


def checkpoint_for_path(path: Path) -> AssetCheckpoint:
    if not path.exists():
        return AssetCheckpoint(exists=False, path_kind="missing", content_digest=None, bytes=None)
    if path.is_dir():
        return AssetCheckpoint(
            exists=True,
            path_kind="directory",
            content_digest=_digest_directory(path),
            bytes=_directory_size(path),
        )
    return AssetCheckpoint(
        exists=True,
        path_kind="file",
        content_digest=_digest_file(path),
        bytes=path.stat().st_size,
    )


def bootstrap_assets(workspace_root: Path) -> tuple[Asset, ...]:
    assets: list[Asset] = []
    project_profile = load_project_profile(workspace_root)
    for node_name, _ in ASSET_PATHS:
        rel_path = resolved_asset_relative_path(workspace_root, node_name)
        path = asset_path(workspace_root, node_name)
        asset_type = asset_declared_type(node_name)
        type_profile = ASSET_TYPES[asset_type]
        checkpoint = checkpoint_for_path(path)
        metadata = {
            "relative_path": rel_path,
            "exists": "true" if path.exists() else "false",
            "path_kind": checkpoint.path_kind,
        }
        if node_name == "code_surface":
            metadata.update(
                {
                    "tenant_name": project_profile.tenant_name,
                    "realization_mode": project_profile.realization_mode,
                    "language": project_profile.language,
                    "test_runner": project_profile.test_runner,
                }
            )
        assets.append(
            Asset(
                asset_id=node_name,
                uri=relative_file_uri(path, workspace_root=workspace_root),
                declared_type=asset_type,
                metadata=metadata,
                provenance=AssetProvenance(
                    model="projected_checkpoint",
                    source="workspace_materialized_state",
                    mutable=type_profile.mutable_default,
                    history_basis="runtime_and_constructive_event_history",
                ),
                checkpoint=checkpoint,
            )
        )
    return tuple(assets)


def bootstrap_input_collection(workspace_root: Path) -> AssetCollection:
    return AssetCollection(name="bootstrap_input_set", assets=bootstrap_assets(workspace_root))


def bootstrap_bindings(workspace_root: Path) -> tuple[AssetNodeBinding, ...]:
    assets = {asset.asset_id: asset for asset in bootstrap_assets(workspace_root)}
    bindings = [
        AssetNodeBinding(node="input_set", asset_ids=INPUT_SET_ASSET_IDS),
    ]
    for node_name, _ in ASSET_PATHS:
        bindings.append(AssetNodeBinding(node=node_name, asset_ids=(node_name,)))
    return tuple(bindings)
