[mypy]
python_version = 3.11
mypy_path = build_tenants/python/code
show_error_codes = True
pretty = True
warn_unused_configs = True

[mypy-genesis.*]
ignore_missing_imports = True

[mypy-gtl.*]
ignore_missing_imports = True

[mypy-odd_sdlc.*]
strict = True
