// Implements: T-184

import type { SdlcWorkerHandoffManifest } from "../../carriers.js";
import {
  SDLC_COMPONENT_CONCERN_ROLES,
  SDLC_DESIGN_COMPLETENESS_STATUSES
} from "../../carriers.js";
import {
  SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND,
  SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_DRAFT_CONTENT_KIND,
  SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_SECTIONS
} from "./content_register.js";
import {
  DESIGN_DEPTH_FP_EVALUATOR_RULE_REF
} from "./design_depth_register.js";

export function designDepthFpEvaluatorPrompt(input: {
  readonly manifest: SdlcWorkerHandoffManifest;
  readonly manifestPath: string;
  readonly governanceRef: string;
  readonly governancePath: string;
  readonly constructionBriefPath: string;
  readonly invocationPackagePath: string;
  readonly workerReportPath: string;
  readonly workerReportSummaryLines: readonly string[];
  readonly contentRegisterPath: string;
  readonly registerProjectionPath: string;
  readonly subworkstreamManifestPath: string;
  readonly selectedCompositionRef: string;
  readonly selectedCompositionDigest: string;
  readonly selectedCompositionSelectionRef: string;
  readonly selectedRegimeBindingRef: string | null;
}): string {
  return [
    "odd_sdlc evaluate.C/F_P design-depth register rule.",
    "",
    "Purpose:",
    "- Populate the implementation design-depth content register as the highest semantic design-depth truth for downstream transforms.",
    "- Evaluate the workspace, admitted transform evidence, worker report, construction brief, invocation package, ADR artifact, and residual pressure together.",
    "- Treat depth as the priority F_P judgment: decide whether the component/module decomposition, source ownership, public boundaries, and residual pressure are proportionate to the requirements.",
    "- For each requirement or requirement group, decide whether it requires separable_public_boundary, shared_component, test_boundary, data_contract_boundary, runtime_or_persistence_boundary, human_review, or blocked handling. Encode that decision in component row publicBoundary/rationale text and designCompletenessVerdict reasons.",
    "- This is evaluation work. Do not rewrite the ADR, source files, tests, package files, or product materialization outputs.",
    "- You may use agent-internal subagents or parallel workstreams as read-only compute strategy for independent modules, interfaces, obligation slices, or evidence packets.",
    `- If you use evaluator subworkstreams, record them in ${input.subworkstreamManifestPath}. Rows must cite authority/dependency inputs, stay read-only over workspace/product files, and remain observation only.`,
    "- Evaluator subworkstreams do not emit ABG events, write ledgers, close edges, select traversal, publish consequence projections, or create ABG branch leases. The parent evaluate.C result owns the final content-register merge.",
    "- The content register path is the durable evaluation artifact; the task is not a single-shot JSON response.",
    `- The system pre-creates that path as a non-admitted draft with selected composition identity and one "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_DRAFT_CONTENT_KIND}" row per register section. Your job is to convert draft rows into semantic "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND}" rows incrementally.`,
    "",
    "Read in order:",
    `1. compressed work-category governance (${input.governanceRef}): ${input.governancePath}`,
    `2. construction brief: ${input.constructionBriefPath}`,
    `3. inspect the pre-created draft content register at ${input.contentRegisterPath}; preserve its top-level selected composition identity.`,
    "4. convert each draft row into a semantic design-depth fragment row from the construction brief, admitted transform evidence, and selected authority refs.",
    "5. only after the first evaluator update, read the ADR or workspace authority refs needed to resolve a specific missing payload section.",
    "",
    "Precomputed worker result report summary:",
    ...input.workerReportSummaryLines.map((line) => `- ${line}`),
    "",
    "Hard pre-register limits:",
    `- Do not use the Read tool on the handoff manifest (${input.manifestPath}). It is too large; summarize selected keys with Node.`,
    `- Do not inspect the worker result report (${input.workerReportPath}) before the first evaluator update. Its compact summary is already in this prompt.`,
    `- Do not use the Read tool on the worker invocation package (${input.invocationPackagePath}) before the first evaluator update. If needed, summarize selected keys with Node.`,
    `- Do not use the Read tool, grep, sed, head, tail, cat, or a summary script on the ADR transform artifact (${input.manifest.outputFile}) before the first evaluator update.`,
    "- Before the first evaluator update, do not inspect extra authority files beyond the governance doc, construction brief, and draft content register.",
    "- The first evaluator content-register update must be your selected evaluate.C/F_P judgment. Do not spend the first pass gathering exhaustive context.",
    "- Do not run a worker-result-report discovery script before the first evaluator update.",
    "- Do not run any bounded-summary action before the first evaluator update. After reading the governance doc, construction brief, and draft content register, the next tool action must publish the content register update.",
    "- Do not say you are writing the register until that file write has succeeded.",
    "- First-update admission policy: convert every draft row to a non-draft fragment row in the existing content register, preserve selected composition identity, publish the same register path atomically, and expose only compact row counts in terminal output.",
    "- Bounded local automation may support summarization, JSON validation, and the first mechanical draft-row conversion only. Do not deterministically construct later semantic register rows from framework rules.",
    "",
    "First register materialization rule:",
    "- After reading the governance doc and construction brief, update the pre-created content register file directly as the selected evaluate.C/F_P semantic pressure map.",
    "- Use admitted upstream design surfaces, dependency pressure, product file targets, tenant stack authority, worker report summary, and specific authority refs as the basis.",
    "- Do not copy a framework-generated register skeleton as semantic truth. If a section is uncertain, emit a partial or blocked axis with explicit reasons and evidence refs instead of inventing rows.",
    `- The content register carries ProductAssetModel rows. Use contentKind "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND}" rows for incremental section writes while you build the register.`,
    "- F_D assembles admitted fragment rows, sorted by payload.sequence, into the legacy register projection. A final full contentKind \"sdlc_design_depth_register\" row is also valid when the complete register is already available.",
    `- Do not write the legacy projection path directly: ${input.registerProjectionPath}`,
    "- The first register can be compact; after it exists, iterate only if validation fails or a specific axis is partial/blocked.",
    "- After the first register exists, perform a mandatory bounded target-path reconciliation pass against the transform artifact and any source authority refs that explicitly name product files.",
    "- In that reconciliation pass, compare fileTargetRows[].relativePath, componentTopologyRows[].relativePath, componentRealizationRows[].relativePath, and firstProductFileToChange against the transform artifact Product File Targets / Component rows and explicit source-authority file paths.",
    "- If those sources name exact product paths, the final register must preserve those exact paths unless an admitted later authority supersedes them; do not shorten, normalize away source directories, or invent sibling paths.",
    "- If the transform artifact and source authority disagree on a target path, cite both refs and choose the path required by the highest source authority. If the conflict cannot be resolved, emit a blocked designCompletenessVerdict axis instead of guessing.",
    "Reading discipline:",
    "- Do not print, cat, tail, grep, or paste full authority files into stdout.",
    "- Do not print full ADR sections, markdown tables, requirement-lineage tables, product-file tables, or component-topology tables into stdout.",
    "- Do not display worker_invocation_package.json, requirement tables, authority ref arrays, evidence arrays, or full JSON objects in the terminal.",
    "- Do not use cat, sed, head, tail, grep, jq '.', or any equivalent command to display the five primary inputs.",
    "- If JSON or Markdown inspection is needed, run Node snippets that read silently and print only bounded counts, selected keys, or at most 20 short ids.",
    "- Keep terminal output bounded and purposeful. Stdout is an agent work trace, not evaluation truth.",
    "- The content register file is the evaluation surface. Prefer file writes and local validation over terminal narration.",
    "",
    "Agentic F_P work loop:",
    "- After the first evaluator update exists, write a short plan and checklist for the required register sections.",
    "- Execute the plan incrementally: each iteration should complete one register section or one small cluster of related sections, then overwrite the same content register with accumulated rows.",
    "- Do not announce, plan, or attempt a full semantic register write in one action after the first update. A hidden full-register synthesis pass violates the content-register visibility contract.",
    "- After the first update, every exploratory read must be paired with the next tool action that writes at least one named non-empty or explicitly blocked register section back to the same content register file.",
    "- The preferred order is stackProfileRows, implementationModuleRows, componentTopologyRows, fileTargetRows, componentRealizationRows, moduleSchemaFragments, moduleStateDiagramFragments, aggregateDomainModelRows, aggregateDomainModel, sunnyDaySequenceRows, aggregateSunnyDaySequence, designCompletenessVerdict.",
    "- When reading the transform ADR after the first update, read it silently with Node, extract only the table or heading range needed for the next named section, and write that section to the register file; do not print the extracted table.",
    "- Time budget is part of correctness: update the draft content register before doing deep exploratory review.",
    "- After the governance doc, construction brief, and draft content register are read, write the first evaluator update before any ADR summary, worker-report inspection, source-authority lookup, or deep exploratory action.",
    `- First evaluator update must convert the existing draft rows into one "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND}" row for every listed register section. Replace each draft rowRef prefix "content-register-row-draft://" with a stable non-draft rowRef such as "content-register-row://". Use null or [] values for intentionally empty sections and use partial/blocked verdict axes when authority is not yet sufficient.`,
    "- The first update may be mechanically seeded from the existing draft payload values; that is acceptable because it creates an admitted pressure map with explicit partial/blocked placeholders. The semantic refinement happens in later section-sized writes.",
    "- First update atomicity shape: read existing JSON, map contentRows so draft contentKind becomes the semantic fragment contentKind, replace the rowRef prefix, preserve selected composition fields, publish the register through an atomic same-path replacement, then print counts only.",
    "- Exact first update command pattern: use Bash with a Node script that reads the existing content register, maps every draft row to a semantic fragment row, writes a temporary JSON file, renames it over the same path, and prints only row counts.",
    "```bash",
    "node --input-type=module <<'NODE'",
    "import { readFile, writeFile, rename } from 'node:fs/promises';",
    `const file = ${JSON.stringify(input.contentRegisterPath)};`,
    `const semanticKind = ${JSON.stringify(SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND)};`,
    `const targetAssetType = ${JSON.stringify(input.manifest.targetAssetType)};`,
    "const register = JSON.parse(await readFile(file, 'utf8'));",
    "let converted = 0;",
    "register.contentRows = register.contentRows.map((row, index) => {",
    "  const next = { ...row, payload: { ...row.payload } };",
    "  if (next.contentKind.endsWith('_draft') || String(next.rowRef).startsWith('content-register-row-draft://')) converted += 1;",
    "  next.contentKind = semanticKind;",
    "  next.rowRef = String(next.rowRef).replace(/^content-register-row-draft:\\/\\//u, 'content-register-row://');",
    "  next.payload.kind = 'sdlc_design_depth_register_fragment';",
    "  next.payload.fragmentVersion = 'ts-design-depth-fragment-v1';",
    "  next.payload.targetAssetType = next.payload.targetAssetType ?? targetAssetType;",
    "  next.payload.sequence = next.payload.sequence ?? index + 1;",
    "  next.payload.mergeMode = 'replace';",
    "  return next;",
    "});",
    "const tmp = `${file}.tmp-${process.pid}`;",
    "await writeFile(tmp, `${JSON.stringify(register, null, 2)}\\n`, 'utf8');",
    "await rename(tmp, file);",
    "console.log(JSON.stringify({ converted, rowCount: register.contentRows.length }));",
    "NODE",
    "```",
    "- Exact second update command pattern: immediately after the first update, use Bash with a Node script that reads the ADR silently, extracts only the simple stack/module/component/file-target tables, writes those named section rows to the same content register, and prints counts only. Do not print table content.",
    "```bash",
    "node --input-type=module <<'NODE'",
    "import { readFile, writeFile, rename } from 'node:fs/promises';",
    `const file = ${JSON.stringify(input.contentRegisterPath)};`,
    `const adrFile = ${JSON.stringify(input.manifest.outputFile)};`,
    "const evidenceRef = new URL(`file://${adrFile}`).href;",
    "const register = JSON.parse(await readFile(file, 'utf8'));",
    "const adr = await readFile(adrFile, 'utf8');",
    "const slug = (value) => String(value).toLowerCase().replace(/`/gu, '').replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '');",
    "const cell = (value) => String(value ?? '').trim().replace(/^`|`$/gu, '').trim();",
    "const sectionText = (heading) => {",
    "  const start = adr.indexOf(`## ${heading}`);",
    "  if (start < 0) return '';",
    "  const next = adr.slice(start + 3).search(/\\n## /u);",
    "  return next < 0 ? adr.slice(start) : adr.slice(start, start + 3 + next);",
    "};",
    "const tableRows = (heading) => sectionText(heading).split('\\n')",
    "  .filter((line) => line.trim().startsWith('|'))",
    "  .filter((line) => !/^\\|\\s*-+/u.test(line.trim()))",
    "  .slice(1)",
    "  .map((line) => line.split('|').slice(1, -1).map(cell));",
    "const stackRows = tableRows('Stack Profile');",
    "const stack = Object.fromEntries(stackRows.map(([layer, selection]) => [layer, selection]));",
    "const moduleRows = tableRows('Module Boundary').map(([moduleName]) => ({",
    "  kind: 'sdlc_implementation_module_row',",
    "  moduleName: cell(moduleName),",
    "  moduleRef: `module://odd-sdlc/${slug(moduleName)}`",
    "}));",
    "const topologyRows = tableRows('Component Topology').map(([componentId, moduleName, relativePath, publicBoundary]) => ({",
    "  kind: 'sdlc_component_topology_row',",
    "  componentId: slug(componentId),",
    "  moduleName: cell(moduleName),",
    "  relativePath: cell(relativePath),",
    "  publicBoundary: cell(publicBoundary),",
    "  concernRole: 'other',",
    "  requirementIds: [],",
    "  sourceAssetRefs: [evidenceRef]",
    "}));",
    "const fileTargetRows = tableRows('Product File Targets').map(([relativePath, role]) => ({",
    "  kind: 'sdlc_file_target_row',",
    "  relativePath: cell(relativePath),",
    "  role: cell(role)",
    "}));",
    "const replacements = new Map([",
    "  ['stackProfileRows', [{",
    "    kind: 'sdlc_stack_profile_row',",
    "    stackRef: 'stack://odd-sdlc/implementation-design',",
    "    language: cell(stack.Language ?? 'unknown'),",
    "    buildTool: cell(stack['Build tool'] ?? 'unknown')",
    "  }]],",
    "  ['implementationModuleRows', moduleRows],",
    "  ['componentTopologyRows', topologyRows],",
    "  ['fileTargetRows', fileTargetRows]",
    "]);",
    "register.contentRows = register.contentRows.map((row) => {",
    "  const section = row.payload?.section;",
    "  if (!replacements.has(section)) return row;",
    "  return {",
    "    ...row,",
    "    contentKind: 'sdlc_design_depth_register_fragment',",
    "    payload: {",
    "      ...row.payload,",
    "      kind: 'sdlc_design_depth_register_fragment',",
    "      fragmentVersion: 'ts-design-depth-fragment-v1',",
    "      mergeMode: 'replace',",
    "      value: replacements.get(section)",
    "    },",
    "    evidenceRefs: Array.from(new Set([...(row.evidenceRefs ?? []), evidenceRef])),",
    "    sourceBasisRefs: Array.from(new Set([...(row.sourceBasisRefs ?? []), evidenceRef]))",
    "  };",
    "});",
    "const tmp = `${file}.tmp-${process.pid}`;",
    "await writeFile(tmp, `${JSON.stringify(register, null, 2)}\\n`, 'utf8');",
    "await rename(tmp, file);",
    "console.log(JSON.stringify({",
    "  stackProfileRows: replacements.get('stackProfileRows').length,",
    "  implementationModuleRows: moduleRows.length,",
    "  componentTopologyRows: topologyRows.length,",
    "  fileTargetRows: fileTargetRows.length",
    "}));",
    "NODE",
    "```",
    "- Then iterate by editing the content register file in place: inspect only the authority needed for a specific missing/partial section, add or replace the corresponding section row, then validate the file.",
    "- The next tool action after any post-first-update ADR or authority inspection must write the corresponding section row. Do not collect multiple large sections before writing.",
    "- A valid progress write may be intentionally partial or blocked, but it must replace the target section row with explicit value, evidenceRefs, and reasons instead of leaving the run in hidden synthesis.",
    "- Do not spend the run enumerating every requirement id before writing the register. Use worker_result_report counts and high-signal samples for pressure; full trace remains in admitted evidence refs and source authority surfaces.",
    "- If time or authority is insufficient, still write a structurally valid content register with partial or blocked designCompletenessVerdict axes and explicit reasons. Draft-row timeout is worse than an admitted pressure map with honest residual pressure.",
    "- It is acceptable to rewrite the content register multiple times while converging. Do not treat this as a single-shot generation task.",
    "- Use scripts or targeted commands to summarize authority and validate JSON shape; do not paste large source or register bodies into stdout.",
    "- Script output budget before first evaluator update: the only script allowed is the same-path draft-to-fragment register update, and it may print only compact row counts.",
    "- If the component/module set is uncertain, encode the uncertainty in partial or blocked designCompletenessVerdict axes and continue with the smallest truthful pressure map.",
    "- If a referenced authority corpus is large, sample the headings/tables needed for module boundaries and requirement ids; do not dump the corpus into the terminal.",
    "- Final response is irrelevant unless the content register exists and validates. Prioritize writing and validating the file over narrative.",
    "",
    `Durable evaluation artifact to create and validate: ${input.contentRegisterPath}`,
    "",
    "Required content register shape:",
    "- kind: \"sdlc_evaluate_content_register\"",
    "- registerVersion: \"ts-evaluate-content-register-v1\"",
    "- stage: \"evaluate.C\"",
    `- ruleRef: "${DESIGN_DEPTH_FP_EVALUATOR_RULE_REF}"`,
    "- ruleRole: \"semantic_judgment\"",
    "- computeMeans: \"F_P\"",
    "- authorityFunction: \"synthesize_model\"",
    `- selectedCompositionRef: "${input.selectedCompositionRef}"`,
    `- selectedCompositionDigest: "${input.selectedCompositionDigest}"`,
    `- selectedCompositionSelectionRef: "${input.selectedCompositionSelectionRef}"`,
    `- selectedRegimeBindingRef: ${input.selectedRegimeBindingRef === null ? "null" : JSON.stringify(input.selectedRegimeBindingRef)}`,
    `- compositionContributionRef: "${input.selectedRegimeBindingRef ?? input.selectedCompositionRef}"`,
    "- sourceBasisRefs[], candidateArtifactRefs[], evidenceRefs[], contentRows[].",
    "- contentRows[] are the incremental register rows. Each row must be a closed carrier with exactly kind, rowRef, authorityFunction, carrierFamily, contentKind, payload, sourceBasisRefs, evidenceRefs.",
    "- contentRows[].kind: \"sdlc_evaluate_content_register_row\"",
    "- contentRows[].rowRef: a stable non-empty ref such as \"content-register-row://odd-sdlc/design-depth/<edgeName>/<section>/<sequence>\"",
    "- contentRows[].authorityFunction: \"synthesize_model\"",
    "- contentRows[].carrierFamily: \"ProductAssetModel\"",
    `- Preferred incremental contentRows[].contentKind: "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND}"`,
    "- Optional final contentRows[].contentKind: \"sdlc_design_depth_register\" when payload is the full design-depth register object below.",
    "- contentRows[].sourceBasisRefs[] must cite the construction brief, governance doc, and any bounded authority inspected for this row.",
    "- contentRows[].evidenceRefs[] must cite the ADR/transform artifact or other admitted evidence supporting this row.",
    "",
    "Incremental fragment payload shape:",
    "- kind: \"sdlc_design_depth_register_fragment\"",
    "- fragmentVersion: \"ts-design-depth-fragment-v1\"",
    "- targetAssetType: \"implementation_design_surface\"",
    `- section: one of ${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_SECTIONS.join(", ")}`,
    "- sequence: positive integer; use increasing numbers so F_D can project the register deterministically.",
    "- mergeMode: \"replace\"",
    "- value: the exact value for that register section, for example the array for componentTopologyRows or null/object for aggregateDomainModel.",
    "- Multiple writes should preserve prior rows and replace or append the section row being advanced. The final admitted register may contain many fragment rows.",
    "- F_D projects fragment rows only after the register contains at least one fragment for every listed register section; emit null or an empty array explicitly for intentionally empty sections.",
    `- F_D ignores "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_DRAFT_CONTENT_KIND}" rows and ignores rowRefs beginning "content-register-row-draft://"; draft rows are scaffolding only, not projectable semantic truth.`,
    "",
    "Embedded ProductAssetModel payload shape:",
    "- kind: \"sdlc_design_depth_register\"",
    "- registerVersion: \"ts-design-depth-v1\"",
    "- targetAssetType: \"implementation_design_surface\"",
    "- stackProfileRows[] with kind, stackRef, language, buildTool",
    "- implementationModuleRows[] with kind, moduleName, moduleRef",
    "- aggregateDomainModelRows[] with kind, modelRef",
    "- moduleSchemaFragments[] with kind, moduleName, entities, operations, requirementIds, sourceAssetRefs",
    "- moduleStateDiagramFragments[] with kind, moduleName, entityId, stateless, states, transitions, requirementIds, sourceAssetRefs",
    "- aggregateDomainModel with kind, modelVersion, entities, operations, crossModuleReferences, evidenceRefs",
    `- aggregateDomainModel.modelVersion must be exactly "ts-design-depth-v1".`,
    "- sunnyDaySequenceRows[] with kind, sequenceRef",
    "- aggregateSunnyDaySequence with kind, sequenceVersion, steps, evidenceRefs",
    `- aggregateSunnyDaySequence.sequenceVersion must be exactly "ts-design-depth-v1".`,
    "- componentTopologyRows[] with kind, componentId, moduleName, relativePath, publicBoundary, concernRole, requirementIds, sourceAssetRefs",
    "- componentRealizationRows[] with kind, componentId, moduleName, relativePath, publicBoundary, trancheId, firstProductFileToChange, upstreamComponentIds, requirementIds, sourceAssetRefs",
    "- fileTargetRows[] with kind, relativePath, role",
    "- designCompletenessVerdict with entity, attribute, and flow axis verdicts.",
    "- designCompletenessVerdict is a closed object with exactly kind, verdictVersion, entity, attribute, flow. Do not emit entityAxis, attributeAxis, flowAxis, axisVerdicts, or any extra designCompletenessVerdict fields.",
    "- Each designCompletenessVerdict axis object is closed with exactly kind, axis, status, reasons, evidenceRefs. Do not add summaries, scores, counts, confidence, coverage, missingItems, or nested axis-specific objects.",
    `- Allowed componentTopologyRows[].concernRole values: ${SDLC_COMPONENT_CONCERN_ROLES.join(", ")}`,
    `- Allowed designCompletenessVerdict.*.status values: ${SDLC_DESIGN_COMPLETENESS_STATUSES.join(", ")}. Use "satisfied" for a complete axis; never use "complete".`,
    "",
    "Nested closed-object contract:",
    "- Do not use string shorthand for typed rows. An array of strings is only valid for fields whose name ends in Ids, Refs, Names, states, reasons, evidenceRefs, sourceAssetRefs, inputEntityIds, outputEntityIds, requiredAttributeIds, invariantRefs, or stateTransitionIds, or the exact sdlc_domain_entity.invariants field.",
    "- moduleSchemaFragments[].entities[] must contain closed sdlc_domain_entity objects with kind, entityId, moduleName, ownership, attributes, invariants, sourceAssetRefs.",
    "- sdlc_domain_entity.invariants must be a string array of compact invariant statements or invariant refs. Structured invariant objects are invalid; put detailed support in evidenceRefs, invariantRefs, or designCompletenessVerdict.reasons instead.",
    "- sdlc_domain_entity.attributes[] must contain closed sdlc_domain_attribute objects with kind, attributeId, name, valueType, cardinality, invariantRefs.",
    "- moduleSchemaFragments[].operations[] and aggregateDomainModel.operations[] must contain closed sdlc_domain_operation objects with kind, operationId, moduleName, inputEntityIds, outputEntityIds, requiredAttributeIds.",
    "- moduleStateDiagramFragments[].transitions[] must contain closed sdlc_entity_state_transition objects with kind, transitionId, fromState, toState, operationId, entityId.",
    "- aggregateDomainModel.entities[] must contain closed sdlc_aggregate_domain_entity objects with kind, entityId, ownerModuleName, attributes, sourceModuleNames.",
    "- aggregateDomainModel.entities[].attributes[] must contain full closed sdlc_domain_attribute objects. Copy or adapt the owning module schema attribute objects; never emit attribute id strings, names, or summaries in this array. If no valid aggregate attributes are needed, use an empty array.",
    "- aggregateDomainModel.crossModuleReferences[] must contain closed objects with fromModuleName, toModuleName, entityId.",
    "- aggregateSunnyDaySequence.steps[] must contain closed sdlc_sunny_day_sequence_step objects with kind, stepId, moduleName, operationId, inputEntityIds, outputEntityIds, stateTransitionIds.",
    `- designCompletenessVerdict must include exactly kind, verdictVersion, entity, attribute, flow. The entity/attribute/flow values must be closed axis verdict objects with exactly kind, axis, status, reasons, evidenceRefs. verdictVersion must be exactly "ts-design-depth-v1". Axis status must be satisfied, partial, or blocked.`,
    "",
    "Minimal nested examples:",
    "- entity: {\"kind\":\"sdlc_domain_entity\",\"entityId\":\"entity:<module>.<name>\",\"moduleName\":\"<module>\",\"ownership\":\"owned\",\"attributes\":[{\"kind\":\"sdlc_domain_attribute\",\"attributeId\":\"attr:<module>.<name>.<field>\",\"name\":\"<field>\",\"valueType\":\"string\",\"cardinality\":\"one\",\"invariantRefs\":[]}],\"invariants\":[],\"sourceAssetRefs\":[\"file://...\"]}",
    "- operation: {\"kind\":\"sdlc_domain_operation\",\"operationId\":\"operation:<module>.<verb>\",\"moduleName\":\"<module>\",\"inputEntityIds\":[],\"outputEntityIds\":[\"entity:<module>.<name>\"],\"requiredAttributeIds\":[]}",
    "- aggregate entity: {\"kind\":\"sdlc_aggregate_domain_entity\",\"entityId\":\"entity:<module>.<name>\",\"ownerModuleName\":\"<module>\",\"attributes\":[{\"kind\":\"sdlc_domain_attribute\",\"attributeId\":\"attr:<module>.<name>.<field>\",\"name\":\"<field>\",\"valueType\":\"string\",\"cardinality\":\"one\",\"invariantRefs\":[]}],\"sourceModuleNames\":[\"<module>\"]}",
    "- transition: {\"kind\":\"sdlc_entity_state_transition\",\"transitionId\":\"transition:<module>.<from>.<to>\",\"fromState\":\"<from>\",\"toState\":\"<to>\",\"operationId\":\"operation:<module>.<verb>\",\"entityId\":\"entity:<module>.<name>\"}",
    "- sequence step: {\"kind\":\"sdlc_sunny_day_sequence_step\",\"stepId\":\"step:<module>.<verb>\",\"moduleName\":\"<module>\",\"operationId\":\"operation:<module>.<verb>\",\"inputEntityIds\":[],\"outputEntityIds\":[\"entity:<module>.<name>\"],\"stateTransitionIds\":[]}",
    "- axis verdict: {\"kind\":\"sdlc_design_completeness_axis_verdict\",\"axis\":\"entity\",\"status\":\"satisfied\",\"reasons\":[\"implementation-design register declares owned entities\"],\"evidenceRefs\":[\"file://...\"]}",
    "",
    "Rules:",
    "- The register is the compact pressure map from design state A to implementation state B; downstream transform.C consumes it as implementation-design truth.",
    "- Prefer a small truthful register over a broad invented architecture, but do not omit source targets, module boundaries, requirement lineage, or stack facts needed to keep pressure on the transformer.",
    "- Register size budget is part of correctness: this evaluator must produce a bounded pressure map, not an exhaustive copy of every requirement table or design paragraph.",
    "- Bounded first-pass register target: one stack profile row, one implementation module row per module, one compact schema fragment per module, at most two entities and two operations per module, one state diagram fragment per module, no more than 18 sunny-day steps, 18 to 32 component rows only when the ADR requires them, and file targets copied from the ADR materialization targets.",
    "- Use feature decomposition rows, ADR component rows, and module/source-root boundaries as the primary component decomposition. Do not derive one component per requirement.",
    "- For a dense full-breadth product, emit 20 to 32 componentTopologyRows/componentRealizationRows when needed; do not exceed 32 component rows without a hard requirement in the ADR.",
    "- Keep moduleSchemaFragments compact: one fragment per implementation module, with representative entities and operations sufficient to preserve transformer pressure. Do not model every possible field, proof artifact, or test case as a separate entity.",
    "- Keep aggregateDomainModel compact: summarize cross-module domain shape with no more than 16 aggregate entities and no more than 24 aggregate operations.",
    "- Keep aggregateSunnyDaySequence compact: use no more than 18 steps that show the main public happy path and proof-output flow.",
    "- Requirement ids on component rows are pressure samples for that component, not a full trace surface. Carry 3 to 8 local/high-signal requirementIds per component row and leave full global trace coverage in the ADR, feature decomposition, and requirement surfaces.",
    "- Do not repeat the same large requirement id list across many rows.",
    "- Use the construction brief stagePressure and target carrier refs to decide which staged authority this register must satisfy.",
    "- Treat the ADR as candidate transform evidence, not the full truth; correct underspecified ADR rows by evaluating the workspace and admitted evidence.",
    "- Use the ADR Product File Targets table for fileTargetRows, but keep fileTargetRows to materialized product file roles.",
    "- Canonical fileTargetRows[].role values are source, test, build_config, design, documentation, or other.",
    "- A source row marked deferred is still a materialized product target; emit it with role source.",
    "- For a trivial product, fileTargetRows must name only downstream materialized product targets such as source, test, or build_config files; do not include the current ADR/design document as a file target.",
    "- componentTopologyRows and componentRealizationRows must not be empty for implementation-design registers.",
    "- Do not collapse the register to manifest-only when source/runtime requirements are present in the ADR requirement lineage, construction brief, invocation package, or worker stderr.",
    "- Requirements that imply separable public/runtime/data/test boundaries must become separate component-level realization rows unless the register gives a specific shared-component rationale in publicBoundary and designCompletenessVerdict.reasons.",
    "- Trivial product override: when the workspace/constraints/ADR identify a trivial product or one tiny executable/script target, keep one componentTopologyRows row and one componentRealizationRows row for the shared source target unless there are separate source files or a hard accepted authority requiring separate product components. Carry runtime, route, response, and proof requirement ids as facets of that one component with an explicit shared-component rationale.",
    "- If accepted authority says a source target is an executable, script, program, CLI, service entrypoint, or must print/emit/respond when run, preserve that executable-entrypoint obligation in publicBoundary and designCompletenessVerdict reasons. Do not downgrade it to an import-only helper boundary unless an admitted authority explicitly says the product is library-only.",
    "- Do not split a trivial single-file service into runtime_binding, response, and proof-support components when all behavior is intentionally implemented in the same source file.",
    "- Fail your own self-check and rewrite if the register assigns unrelated source/runtime/data/test obligations to one coarse component without a specific cohesion rationale.",
    "- When a requirement lineage row says a source obligation is deferred to a downstream source-materialization edge, create the implementation component topology/realization row for that source target now and carry the deferred requirement id on that component.",
    "- Staged decomposition admission is mandatory: each componentTopologyRows[] or componentRealizationRows[] row must own no more than 8 requirementIds.",
    "- If one module or source root owns more than 8 requirement ids, split it into multiple component rows under the same module/source root with distinct componentIds and publicBoundary values.",
    "- Keep upstreamComponentIds as component ids only; never use requirement ids as upstream component ids.",
    "- Target enough componentRealizationRows so component-row pressure density remains 8 or less without copying the full global requirement surface into every row.",
    "- Before final response, reject and rewrite the register if any component row has more than 8 requirementIds or repeats a global requirement list.",
    "- Every componentTopologyRows[].relativePath and componentRealizationRows[].relativePath must have a matching fileTargetRows entry with role source.",
    "- If the ADR repeats the same file path for behavioral roles such as runtime_binding, route, response, smoke proof, execution proof, or deferred implementation behavior, emit one fileTargetRows entry with the materialization role and carry those behavioral requirement ids on componentTopologyRows/componentRealizationRows instead.",
    "- Use only source/application implementation targets for componentTopologyRows and componentRealizationRows.",
    "- If a path is a package, build config, runtime config, documentation, or test/proof target, it must not appear in componentTopologyRows or componentRealizationRows merely to satisfy the source-row rule.",
    "- Do not turn test, proof-test, package, runtime-config, documentation, or build-context targets into implementation components; keep those only in fileTargetRows.",
    "- componentId and moduleName must be stable identifier tokens without spaces; prefer lowercase words joined by '-' or '_'.",
    "- publicBoundary must be a meaningful product behavior or module contract from the ADR; do not use placeholders such as implementation-core, module-root, component, or target.",
    "- concernRole must be one of the allowed values exactly; use \"other\" for simple executable entrypoints or glue unless admitted source authority clearly maps the component to parser, validator, mapper, error_model, io_adapter, reporting, or domain_model.",
    "- Preserve requirement ids exactly as written in the ADR or construction brief.",
    "- Use file:// evidence refs for the ADR transform artifact.",
    "- If the product is trivial, keep the register trivial; do not invent modules, entities, APIs, persistence, or multiple same-file components.",
    "- designCompletenessVerdict evaluates the implementation-design surface only. Do not mark an axis partial or blocked merely because source materialization, test design, execution, or runtime proof happens on a downstream edge.",
    "- Before the final response, re-open the JSON you wrote and verify that every typed nested item above is an object with exactly the declared fields, not a string, Markdown paragraph, or partial object.",
    "- Before the final response, run a bounded path-integrity self-check: every source-role fileTargetRows[].relativePath and every component source relativePath must either appear in the transform artifact target/component tables or be justified by a higher source authority ref cited in sourceBasisRefs/evidenceRefs.",
    "- The path-integrity self-check is mandatory even when the first register was structurally valid; structural validity alone is not enough if exact product file paths drift from the admitted design/source authority.",
    "- Self-check the size budget before final response: component rows are between 1 and 32, every component row has 8 or fewer requirementIds, aggregate entities are 16 or fewer, aggregate operations are 24 or fewer, and sunny-day steps are 18 or fewer.",
    `- Required self-check before final response: run a local JSON check over the content register file and rewrite until it passes. At minimum, verify every contentRows[] entry has exactly kind, rowRef, authorityFunction, carrierFamily, contentKind, payload, sourceBasisRefs, evidenceRefs; verify every "${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_CONTENT_KIND}" payload has exactly kind, fragmentVersion, targetAssetType, section, sequence, mergeMode, value; verify fragment sections are only ${SDLC_DESIGN_DEPTH_REGISTER_FRAGMENT_SECTIONS.join(", ")}; verify any final "sdlc_design_depth_register" payload has registerVersion exactly "ts-design-depth-v1"; when non-null, verify aggregateDomainModel.modelVersion, aggregateSunnyDaySequence.sequenceVersion, and designCompletenessVerdict.verdictVersion are exactly "ts-design-depth-v1"; when designCompletenessVerdict is non-null, verify Object.keys(designCompletenessVerdict).sort() is exactly ["attribute","entity","flow","kind","verdictVersion"] and each axis object at designCompletenessVerdict.entity, .attribute, and .flow has exactly ["axis","evidenceRefs","kind","reasons","status"]; verify moduleSchemaFragments[].entities[].invariants is an array and every invariant item is a string; verify register arrays contain objects, not strings: stackProfileRows, implementationModuleRows, aggregateDomainModelRows, moduleSchemaFragments, moduleSchemaFragments[].entities, moduleSchemaFragments[].entities[].attributes, moduleSchemaFragments[].operations, moduleStateDiagramFragments, moduleStateDiagramFragments[].transitions, aggregateDomainModel.entities, aggregateDomainModel.entities[].attributes, aggregateDomainModel.operations, aggregateDomainModel.crossModuleReferences, aggregateSunnyDaySequence.steps, componentTopologyRows, componentRealizationRows, fileTargetRows.`,
    "- Do not run another exploratory command after deciding the component/module set; write the content register file first, then validate that file.",
    `- Self-check target file: ${input.contentRegisterPath}`,
    "- Do not include Markdown fences, explanation, comments, or trailing prose in the content register file.",
    "- After writing the content register, respond with a one-line summary only."
  ].join("\n");
}

export function reviewGradeEdgeFulfillmentPrompt(input: {
  readonly manifest: SdlcWorkerHandoffManifest;
  readonly governanceRef: string;
  readonly governancePath: string;
  readonly constructionBriefPath: string;
  readonly invocationPackagePath: string;
  readonly workerReportPath: string;
  readonly assessmentPath: string;
  readonly subworkstreamManifestPath: string;
}): string {
  return [
    "odd_sdlc evaluate.C/F_P review-grade edge fulfillment rule.",
    "",
    "Purpose:",
    "- Review the generated asset against incoming requirements, accepted upstream authority, stage boundary, evidence, and likely failure modes.",
    "- This is semantic evaluation work. Do not rewrite source, tests, design artifacts, reports, ledgers, or framework files.",
    "- You may use agent-internal subagents or parallel workstreams as read-only compute strategy for independent modules, obligation slices, or evidence packets.",
    `- If you use evaluator subworkstreams, record them in ${input.subworkstreamManifestPath}. Rows must cite authority/dependency inputs, leave write/output-allocation fields empty, and remain observation only.`,
    "- Evaluator subworkstreams do not emit ABG events, write ledgers, close edges, select traversal, publish consequence projections, or create ABG branch leases. The parent evaluate.C result owns the final assessment merge.",
    "- The assessment file is an evaluation sidecar consumed by the existing SdlcWorkerObligationAssessment -> SdlcEdgeFulfillmentLedger path. It is not a new closure ledger.",
    "",
    "Read in order:",
    `1. compressed work-category governance (${input.governanceRef}): ${input.governancePath}`,
    `2. construction brief: ${input.constructionBriefPath}`,
    `3. invocation package: ${input.invocationPackagePath}`,
    `4. worker result report: ${input.workerReportPath}`,
    "5. generated asset artifacts named by worker_result_report.materializedFiles.",
    "6. product_materialization_manifest.json in the same archive when present.",
    "7. accepted design-depth register refs from construction_brief.stagePressure.designDepthEvaluatorRegisterRefs when present.",
    "",
    "Reading discipline:",
    "- Do not print full files, full JSON objects, full requirement tables, or full source files to stdout.",
    "- Use targeted scripts that print compact counts or short ids only.",
    "- Terminal output is a work trace. The JSON assessment file is the evaluation truth.",
    "- If reviewedObligationIds is large, create the assessment with a short local script: load worker_result_report, map every fulfilled carryover row to a compact fulfilled finding, explicitly override only open findings, write JSON to the assessment path, then parse it back.",
    "- Do not manually type or stream a large findings array through stdout. Write the durable JSON file and print only compact status counts.",
    "- Do not leave background jobs running. If an executable/service must be started to gather evidence, run it inside one bounded shell block, store its PID in a variable, install a trap that kills and waits for that PID on exit, and print only the observed exit/status summary.",
    "- Do not use shell job-control cleanup such as `kill %1` or Claude background tasks for execution probes. A passed assessment is invalid if a spawned service/process remains live after the probe.",
    "",
    `Durable assessment artifact to create and validate: ${input.assessmentPath}`,
    "",
    "Required JSON shape:",
    "- kind: \"sdlc_review_grade_edge_fulfillment_assessment\"",
    "- assessmentVersion: \"ts-review-grade-v1\"",
    `- graphFunctionName: ${JSON.stringify(input.manifest.graphFunctionName)}`,
    `- edgeName: ${JSON.stringify(input.manifest.edgeName)}`,
    `- targetAssetType: ${JSON.stringify(input.manifest.targetAssetType)}`,
    "- status: \"passed\" or \"blocked\"",
    "- reviewedObligationIds: every obligation id from worker_result_report.obligationAssessments and invocation package inline obligations",
    "- findings[]: one sdlc_review_grade_obligation_finding per reviewed obligation id",
    "- evidenceRefs: refs for the assessment, generated assets, accepted authority, and review evidence",
    "- summary: one compact sentence",
    "- No other top-level keys are allowed.",
    "",
    "Finding shape:",
    "- kind: \"sdlc_review_grade_obligation_finding\"",
    "- obligationId: exact obligation id",
    "- fulfillmentStatus: fulfilled, partial, blocked, or unassessed",
    "- failureClass: null when fulfilled, otherwise one of trace_missing, semantic_not_realized, boundary_collapsed, wrong_stage, schema_invalid, execution_environment, test_overlap_missing",
    "- requiredAction: null when fulfilled, otherwise the concrete work item the next transform must complete",
    "- evidenceRefs: generated asset refs and diagnostic refs used for this judgment",
    "- acceptedAuthorityRefs: non-empty requirement/design/depth/test/target-carrier authority refs used for this judgment",
    "- fulfillmentBinding: null unless this finding is a fulfilled component_code_surface finding. On component_code_surface, every fulfilled finding must provide it, including target_asset, source_asset, module, source_set, inline, aggregate, and requirement rows.",
    "- rationale: compact reason for the judgment",
    "- No other finding keys are allowed. Do not add helper booleans, carryover flags, scores, sourceAssetCarryover, sourceAssetStatus, confidence, or notes fields.",
    "",
    "fulfillmentBinding shape when required:",
    "- kind: \"sdlc_requirement_function_fulfillment_binding\"",
    "- requirementRef: exact obligation id",
    "- productRequirementRef: accepted product requirement ref or exact obligation id when no narrower product-requirement ref exists",
    "- designObligationRef: accepted design/depth/component row ref that assigned the obligation",
    "- componentRef: accepted component/module ref",
    "- productTargetRef: target carrier or declared product-file target ref",
    "- codeSurfaceRef: generated source file/API/route/CLI/service ref",
    "- functionOrEntrypointRef: concrete function, exported API, route, CLI command, service entrypoint, executable script, or equivalent public behavior ref",
    "- realizationEvidenceRefs: source/runtime evidence refs proving the binding",
    "- testOrExecutionEvidenceRefs: test, execution, or evaluator evidence refs that hold the binding to account",
    "- evaluatorFindingRef: stable finding ref for this evaluation finding",
    "",
    "Review rules:",
    "- A requirement tag, file path, schema-valid report, or passing smoke output is evidence, not proof by itself.",
    "- Every finding must include at least one acceptedAuthorityRef. Do not emit an empty acceptedAuthorityRefs array for target_asset, source_set, inline, or aggregate findings.",
    "- For target_asset findings, use the construction brief targetCarrierProjection target carrier refs plus the accepted authority files that governed the generated asset.",
    "- Mark partial or blocked when an asset exists but does not plausibly implement the accepted responsibility.",
    "- Mark boundary_collapsed when generated source collapses multiple accepted component rows back into a coarse facade.",
    "- Mark semantic_not_realized when requirement tags are present but the behavior is absent, stubbed, placeholder, or not connected to the exported/public boundary.",
    "- Mark semantic_not_realized when accepted authority requires executable/script/program behavior but the source only exports a helper or function and has no entrypoint path that runs the product behavior when the file is invoked. A test calling a helper is overlap evidence, not executable-product proof.",
    "- For non-materialized planning surfaces such as intent, requirement, design, schedule, or test-design surfaces, do not mark downstream implementation/runtime obligations semantic_not_realized merely because implementation behavior is absent on the current edge.",
    "- When worker_result_report.obligationAssessments already carries a requirement with blockingReasons starting requirement_carried_for_downstream_closure: or requirement_recorded_for_future_closure: and the generated asset, selected target carrier, worker report, or materialization manifest maps that requirement to downstream component/source/realization pressure, mark that finding partial with failureClass wrong_stage and requiredAction naming the downstream materialization/design edge.",
    "- For requirement_surface and other non-materialized planning surfaces, an exact worker_result_report obligation assessment with requirement_recorded_for_future_closure: is accepted lineage for downstream transformation-set carryover; do not require the native markdown asset to repeat every exact requirement id when the report/carrier already preserves the id and accepted authority refs.",
    "- wrong_stage is only for lawful downstream carryover. If the current asset omits the requirement mapping, loses accepted authority, invents an owner, or claims executable fulfillment on the wrong edge, use trace_missing, semantic_not_realized, boundary_collapsed, or schema_invalid instead.",
    "- Requirement lineage is transformer-owned semantic evidence, not a postflight closure shortcut. Inspect worker_result_report.materializedFiles, product_materialization_manifest.files, selected target-carrier materializedFiles, and native file tags/comments where the file format permits them.",
    "- Mark trace_missing when a generated product file is used as fulfillment evidence but carries no lineage in the asset itself, selected target carrier, worker report, or materialization manifest. Do not pass by file existence, digest, or test success alone.",
    "- For every component_code_surface fulfilled finding, bind obligationId -> product requirement when available -> design/depth obligation -> component/product target -> function/API/route/CLI/entrypoint -> evidence in fulfillmentBinding.",
    "- For component_code_surface source_asset, module, target_asset, source_set, inline, or aggregate findings, use the exact obligationId as requirementRef and productRequirementRef when no narrower product requirement exists, but still bind the finding to the concrete generated entrypoint/public behavior and evidence.",
    "- A fulfilled component_code_surface finding with fulfillmentBinding:null is invalid and will be retried, even when the obligation is module-level or source-asset-level carryover.",
    "- Mark semantic_not_realized or schema_invalid when tenant stack authority contradicts emitted product files, for example declaring one module system while generated source/test syntax requires another. The worker must repair the authority surface or the product files; documenting an override in prose is not enough.",
    "- When the generated asset includes a declared executable or test execution contract that can run locally without network or destructive side effects, execute it from the declared working directory and use the observed exit/stdout/stderr as evaluation evidence. If it fails, mark the relevant obligation blocked with execution_environment or semantic_not_realized instead of passing by inspection.",
    "- Mark test_overlap_missing when accepted depth requires test overlap and the generated tests do not exercise the responsibility.",
    "- For component_code_surface, compare source files to accepted design-depth componentRealizationRows and fileTargetRows.",
    "- For materialization-required component_code_surface, compare worker_result_report.materializedFiles and product_materialization_manifest files to declared product-file targets.",
    "- Mark boundary_collapsed or wrong_stage when worker_result_report.materializedFiles or product_materialization_manifest files list undeclared build/test byproducts or extra product files as materialized product truth.",
    "- Build outputs, dependency caches, lockfiles, coverage directories, and transient execution artifacts are not fulfillment proof unless they are declared product targets. Allowed execution byproducts may remain only as byproducts, not as product-file fulfillment evidence.",
    "- For component_test_surface, compare generated tests to accepted testcase/test-design authority and source responsibilities.",
    "- For every other target asset type, compare the generated asset to incoming obligations, accepted upstream authority, target carrier expectations, stage boundary, and evidence overlap.",
    "- If all reviewed obligations are fulfilled, status must be passed and every finding failureClass/requiredAction must be null.",
    "- If any reviewed obligation is partial, blocked, or unassessed, status must be blocked and every non-fulfilled finding must include failureClass and requiredAction.",
    "- Before final response, re-open and parse the assessment JSON. Verify the top-level key set is exactly kind, assessmentVersion, graphFunctionName, edgeName, targetAssetType, status, reviewedObligationIds, findings, evidenceRefs, summary.",
    "- Verify every finding key set is exactly kind, obligationId, fulfillmentStatus, failureClass, requiredAction, evidenceRefs, acceptedAuthorityRefs, fulfillmentBinding, rationale.",
    "- Rewrite until it is valid whole-file JSON with no Markdown fences, comments, trailing prose, or extra keys.",
    "- Final response must be one line: reviewStatus=<passed|blocked> reviewed=<n> blocked=<n>."
  ].join("\n");
}
